(()=>{
  if(globalThis.showSuccessToast)return;
  let timer;
  function ensure(){
    let toast=document.querySelector('[data-global-success-toast]');if(toast)return toast;
    const style=document.createElement('style');style.textContent='.global-success-toast{position:fixed;z-index:9999;right:22px;bottom:22px;width:min(400px,calc(100% - 32px));display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:12px;padding:16px 17px;background:#071a17;color:#fff;border-left:5px solid #18a995;box-shadow:0 20px 60px rgba(7,26,23,.32);transform:translateY(18px);opacity:0;pointer-events:none;transition:.25s ease}.global-success-toast.is-visible{transform:none;opacity:1;pointer-events:auto}.global-success-toast i{display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:#d7f06a;color:#071a17;font-style:normal;font-weight:800}.global-success-toast strong,.global-success-toast span{display:block}.global-success-toast strong{font:600 13px Syne,Arial}.global-success-toast span{color:#b9c7c3;font:11px/1.45 Inter,Arial}.global-success-toast button{border:0;background:transparent;color:#fff;font-size:22px}@media(prefers-reduced-motion:reduce){.global-success-toast{transition:none}}';document.head.append(style);
    toast=document.createElement('div');toast.className='global-success-toast';toast.dataset.globalSuccessToast='';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');toast.innerHTML='<i>✓</i><div><strong>Success</strong><span></span></div><button type="button" aria-label="Dismiss">×</button>';toast.querySelector('button').addEventListener('click',()=>toast.classList.remove('is-visible'));document.body.append(toast);return toast;
  }
  globalThis.showSuccessToast=(message,title='Success')=>{const toast=ensure();toast.querySelector('strong').textContent=title;toast.querySelector('span').textContent=String(message||'Completed successfully.');toast.classList.add('is-visible');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('is-visible'),5500)};
  addEventListener('arkhimar:success',event=>globalThis.showSuccessToast(event.detail?.message,event.detail?.title));
  const nativeFetch=globalThis.fetch?.bind(globalThis);if(nativeFetch)globalThis.fetch=async(input,options={})=>{const response=await nativeFetch(input,options),method=String(options.method||input?.method||'GET').toUpperCase();try{const url=new URL(typeof input==='string'?input:input.url,location.href);if(response.ok&&url.origin===location.origin&&url.pathname.startsWith('/api/')&&['POST','PUT','PATCH','DELETE'].includes(method))queueMicrotask(()=>globalThis.showSuccessToast('Your work was completed successfully.','Success'))}catch{}return response};
})();
