import {createHmac,timingSafeEqual} from 'node:crypto';import {z} from 'zod';import {sendJson} from '../_lib/server.js';import {AI_TOOLS,authorize,automationTemplates,chatSchema,fallbackAnswer,modelAnswer,newId,requireAiActor,routeMessage,snapshot} from '../_lib/ai.js';

const actionSchema=z.object({workspaceId:z.string().uuid(),projectId:z.string().uuid(),conversationId:z.string().uuid().nullable().optional(),toolName:z.string().min(2).max(80),args:z.record(z.string(),z.unknown()).default({}),idempotencyKey:z.string().uuid()}).strict();
const executeSchema=z.object({workspaceId:z.string().uuid(),projectId:z.string().uuid(),proposalId:z.string().uuid(),confirmed:z.literal(true)}).strict();
const feedbackSchema=z.object({workspaceId:z.string().uuid(),projectId:z.string().uuid().nullable().optional(),conversationId:z.string().uuid(),messageId:z.string().uuid().nullable().optional(),rating:z.enum(['helpful','incorrect']),comment:z.string().trim().max(2000).default('')}).strict();
const automationSchema=z.object({workspaceId:z.string().uuid(),projectId:z.string().uuid(),templateId:z.string().min(2).max(80),enabled:z.boolean(),config:z.record(z.string(),z.unknown()).default({})}).strict();
const voiceSchema=z.object({workspaceId:z.string().uuid(),projectId:z.string().uuid(),voiceId:z.string().min(2).max(80),consentToAudio:z.literal(true),recordingDisclosureAccepted:z.boolean(),channel:z.enum(['browser_voice','phone']).default('browser_voice')}).strict();
const voices=[['professional-female','Professional Female','neutral','Clear and composed'],['professional-male','Professional Male','neutral','Measured and direct'],['mature-female','Mature Female','neutral','Assured and calm'],['mature-male','Mature Male','neutral','Experienced and steady'],['warm-guide','Warm Guide','neutral','Supportive onboarding'],['site-coordinator','Calm Site Coordinator','Nigerian English','Clear field coordination']].map(([id,label,accent,description])=>({id,provider:'openai',providerVoiceId:id,label,accent,languages:['en'],description,enabled:true}));
const parse=(schema,body,res)=>{const result=schema.safeParse(body);if(!result.success){sendJson(res,400,{error:'invalid_request'});return null}return result.data};

async function chat(req,res){const v=parse(chatSchema,req.body,res);if(!v)return;const actor=await requireAiActor(req,v.workspaceId,v.projectId),snap=snapshot(actor),route=routeMessage(v.message,v.mode);let result;try{result=await modelAnswer(v.message,snap,route)}catch(error){console.error('ai_provider_degraded',error.message);result=fallbackAnswer(v.message,snap,route)}const conversationId=v.conversationId||newId(),citations=result.citations||(snap.project?[{label:`${snap.project.code} project record`,entityType:'project',entityId:snap.project.id,version:snap.project.sourceVersion}]:[]),proposals=(result.proposedActions||[]).filter(x=>x&&x.toolName).map(item=>({id:newId(),...item,riskLevel:AI_TOOLS[item.toolName]?.risk||'R4',authorization:authorize(actor,item.toolName)}));if(v.retain){await actor.db.from('ai_conversations').upsert({id:conversationId,workspace_id:v.workspaceId,project_id:v.projectId||null,user_id:actor.user.id,channel:'text',retention_mode:'standard',updated_at:new Date().toISOString()});await actor.db.from('ai_messages').insert([{conversation_id:conversationId,role:'user',content:{text:v.message}},{conversation_id:conversationId,role:'assistant',content:{text:result.answer,route,confidence:result.confidence,suggestions:result.suggestions||[]},citations}])}await actor.db.from('ai_audit_events').insert({workspace_id:v.workspaceId,project_id:v.projectId||null,actor_id:actor.user.id,event_type:'chat.completed',channel:'text',details:{route,retained:v.retain,proposal_count:proposals.length}});return sendJson(res,200,{conversationId,route,answer:result.answer,confidence:result.confidence||'medium',citations,suggestions:result.suggestions||[],proposedActions:proposals,provider:process.env.OPENAI_API_KEY?'configured':'grounded-fallback'})}
async function context(req,res){const actor=await requireAiActor(req,String(req.query.workspaceId||''),req.query.projectId||null);return sendJson(res,200,{context:snapshot(actor),role:actor.role,health:{assistant:process.env.OPENAI_API_KEY?'available':'degraded',voice:Boolean(process.env.OPENAI_API_KEY),telephony:Boolean(process.env.VAPI_API_KEY)}})}
async function preview(req,res){const v=parse(actionSchema,req.body,res);if(!v)return;const actor=await requireAiActor(req,v.workspaceId,v.projectId),tool=AI_TOOLS[v.toolName];if(!tool)return sendJson(res,400,{error:'unknown_tool'});const decision=authorize(actor,v.toolName),status=tool.risk==='R4'?'prohibited':decision.requiresApproval?'awaiting_approval':'ready',{data,error}=await actor.db.from('ai_action_proposals').upsert({id:newId(),conversation_id:v.conversationId||null,workspace_id:v.workspaceId,project_id:v.projectId,requested_by:actor.user.id,tool_name:v.toolName,risk_level:tool.risk,args:v.args,status,idempotency_key:v.idempotencyKey},{onConflict:'workspace_id,idempotency_key'}).select().single();if(error)throw error;return sendJson(res,200,{proposal:data,authorization:decision,preview:{label:tool.label,riskLevel:tool.risk,changes:v.args}})}
async function execute(req,res){const v=parse(executeSchema,req.body,res);if(!v)return;const actor=await requireAiActor(req,v.workspaceId,v.projectId),{data:proposal}=await actor.db.from('ai_action_proposals').select('*').eq('id',v.proposalId).eq('workspace_id',v.workspaceId).eq('project_id',v.projectId).maybeSingle();if(!proposal)return sendJson(res,404,{error:'proposal_not_found'});if(proposal.status==='executed')return sendJson(res,200,{ok:true,idempotent:true,proposal});const decision=authorize(actor,proposal.tool_name),tool=AI_TOOLS[proposal.tool_name];if(!decision.allowed)return sendJson(res,tool?.risk==='R4'?403:409,{error:decision.reason,requiresApproval:Boolean(decision.requiresApproval)});if(!['R1','R2'].includes(tool.risk))return sendJson(res,409,{error:'unsupported_execution'});await actor.db.from('audit_events').insert({workspace_id:v.workspaceId,project_id:v.projectId,actor_user_id:actor.user.id,action:tool.risk==='R1'?'drafted':'created',entity_type:proposal.tool_name,entity_id:proposal.id,metadata:{source:'arkhimar_intelligence',proposal_id:proposal.id}});const {data,error}=await actor.db.from('ai_action_proposals').update({status:'executed',executed_at:new Date().toISOString()}).eq('id',proposal.id).select().single();if(error)throw error;return sendJson(res,200,{ok:true,proposal:data,undoAvailable:tool.risk==='R2'})}
async function feedback(req,res){const v=parse(feedbackSchema,req.body,res);if(!v)return;const actor=await requireAiActor(req,v.workspaceId,v.projectId);await actor.db.from('ai_feedback').insert({workspace_id:v.workspaceId,project_id:v.projectId||null,conversation_id:v.conversationId,message_id:v.messageId||null,user_id:actor.user.id,rating:v.rating,comment:v.comment});return sendJson(res,201,{ok:true})}
async function automations(req,res){const parsed=req.method==='POST'?automationSchema.safeParse(req.body):null;if(parsed&&!parsed.success)return sendJson(res,400,{error:'invalid_request'});const workspaceId=parsed?.data.workspaceId||String(req.query.workspaceId||''),projectId=parsed?.data.projectId||String(req.query.projectId||''),actor=await requireAiActor(req,workspaceId,projectId);if(req.method==='GET'){const {data}=await actor.db.from('ai_automations').select('*').eq('workspace_id',workspaceId).eq('project_id',projectId).is('archived_at',null),current=new Map((data||[]).map(x=>[x.template_id,x]));return sendJson(res,200,{automations:automationTemplates.map(x=>({...x,...current.get(x.id)}))})}if(!actor.permissions.includes('write'))return sendJson(res,403,{error:'permission_denied'});const v=parsed.data,template=automationTemplates.find(x=>x.id===v.templateId);if(!template)return sendJson(res,400,{error:'unknown_template'});const {data,error}=await actor.db.from('ai_automations').upsert({workspace_id:workspaceId,project_id:projectId,template_id:v.templateId,name:template.name,enabled:v.enabled,config:v.config,approval_required:true,updated_by:actor.user.id},{onConflict:'workspace_id,project_id,template_id'}).select().single();if(error)throw error;return sendJson(res,200,{automation:data})}
async function catalog(req,res){await requireAiActor(req,String(req.query.workspaceId||''),req.query.projectId||null);return sendJson(res,200,{voices,voiceCloning:false,disclosureRequired:true})}
async function voice(req,res){const v=parse(voiceSchema,req.body,res);if(!v)return;const actor=await requireAiActor(req,v.workspaceId,v.projectId);if(v.channel==='phone'&&!process.env.VAPI_API_KEY)return sendJson(res,503,{error:'telephony_not_configured'});const sessionId=newId();await actor.db.from('ai_audit_events').insert({workspace_id:v.workspaceId,project_id:v.projectId,actor_id:actor.user.id,event_type:'voice.session.started',channel:v.channel,details:{session_id:sessionId,voice_id:v.voiceId,recording_disclosure:v.recordingDisclosureAccepted}});return sendJson(res,201,{sessionId,channel:v.channel,transcriptRequired:true,transport:v.channel==='phone'?'vapi':'browser',status:'ready'})}
function vapi(req,res){const secret=process.env.VAPI_WEBHOOK_SECRET,signature=String(req.headers['x-vapi-signature']||'');if(!secret||!signature)return sendJson(res,401,{error:'invalid_signature'});const expected=createHmac('sha256',secret).update(JSON.stringify(req.body||{})).digest('hex');try{if(!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return sendJson(res,401,{error:'invalid_signature'})}catch{return sendJson(res,401,{error:'invalid_signature'})}return sendJson(res,200,{ok:true,accepted:String(req.body?.message?.type||req.body?.type||'unknown'),toolResults:[]})}

export default async function handler(req,res){const action=String(req.query.action||''),methods={chat:['POST',chat],context:['GET',context],preview:['POST',preview],execute:['POST',execute],feedback:['POST',feedback],automations:['GET,POST',automations],catalog:['GET',catalog],voice:['POST',voice],vapi:['POST',vapi]},route=methods[action];if(!route)return sendJson(res,404,{error:'route_not_found'});if(!route[0].split(',').includes(req.method))return sendJson(res,405,{error:'method_not_allowed'});try{return await route[1](req,res)}catch(error){console.error(`ai_${action}_failed`,error.message);return sendJson(res,error.statusCode||500,{error:error.code||`${action}_failed`,message:error.message})}}
