const path=location.pathname.replace(/\/$/,'')||'/carcare';
const style=document.createElement('style');style.textContent=`.cc-help-launchers{position:fixed;right:20px;bottom:20px;z-index:70;display:flex;gap:9px}.cc-help-launchers button{border:0;border-radius:999px;padding:12px 16px;background:#071a17;color:#fff;box-shadow:0 12px 34px rgba(7,26,23,.25);font:700 10px Inter;letter-spacing:.05em}.cc-help-launchers button:first-child{background:#d7f06a;color:#071a17}.cc-chat{position:fixed;z-index:75;right:20px;bottom:74px;width:min(390px,calc(100% - 30px));background:#fffdf8;border:1px solid #d7d9cf;box-shadow:0 22px 70px rgba(7,26,23,.28)}.cc-chat[hidden],.cc-tour[hidden]{display:none}.cc-chat-head{display:flex;justify-content:space-between;align-items:center;padding:18px;background:#071a17;color:#fff}.cc-chat-head strong{font:600 16px Syne}.cc-chat-head button{border:0;background:transparent;color:#fff;font-size:22px}.cc-chat-log{max-height:310px;overflow:auto;padding:18px;display:grid;gap:10px}.cc-chat-message{max-width:88%;padding:11px 13px;background:#e5f5ee;font-size:12px;line-height:1.55}.cc-chat-message.is-user{justify-self:end;background:#071a17;color:#fff}.cc-chat-choices{display:flex;flex-wrap:wrap;gap:7px;padding:0 18px 18px}.cc-chat-choices button{border:1px solid #18a995;background:#fff;color:#0d2622;padding:8px 10px;font-size:10px}.cc-chat-form{display:flex;border-top:1px solid #d7d9cf}.cc-chat-form input{flex:1;min-width:0;border:0;padding:14px}.cc-chat-form button{border:0;background:#18a995;color:#fff;padding:0 16px}.cc-tour{position:fixed;inset:0;z-index:90;background:rgba(7,26,23,.66)}.cc-tour-card{position:absolute;width:min(410px,calc(100% - 28px));background:#fffdf8;padding:24px;box-shadow:0 18px 70px rgba(0,0,0,.28)}.cc-tour-card small{font:700 9px DM Mono;color:#18a995;letter-spacing:.1em}.cc-tour-card h2{font:600 25px/1.05 Syne;margin:9px 0}.cc-tour-card p{color:#52635f}.cc-tour-actions{display:flex;justify-content:space-between;gap:8px;margin-top:18px}.cc-tour-actions button{border:1px solid #071a17;background:#fff;padding:9px 13px;font-size:10px}.cc-tour-actions button:last-child{background:#071a17;color:#fff}.cc-tour-focus{position:relative;z-index:91!important;outline:5px solid #d7f06a!important;outline-offset:6px}.cc-tour-welcome{position:fixed;right:20px;bottom:78px;z-index:69;width:min(330px,calc(100% - 30px));padding:16px;background:#e5f5ee;border-left:5px solid #18a995;box-shadow:0 14px 45px rgba(7,26,23,.2);font-size:12px}.cc-tour-welcome button{float:right;border:0;background:transparent;font-size:18px}@media(max-width:620px){.cc-help-launchers{right:12px;bottom:12px}.cc-chat{right:12px;bottom:68px}.cc-tour-card{left:14px!important;top:auto!important;bottom:14px}.cc-tour-welcome{right:12px;bottom:68px}}@media print{.cc-help-launchers,.cc-chat,.cc-tour,.cc-tour-welcome{display:none!important}}`;document.head.append(style);

const launcher=document.createElement('div');launcher.className='cc-help-launchers';launcher.innerHTML='<button type="button" data-tour-open>Take a tour</button><button type="button" data-chat-open>Ask CarCare</button>';document.body.append(launcher);
const chat=document.createElement('section');chat.className='cc-chat';chat.hidden=true;chat.setAttribute('aria-label','CarCare assistant');chat.innerHTML='<div class="cc-chat-head"><strong>CarCare assistant</strong><button type="button" aria-label="Close assistant">×</button></div><div class="cc-chat-log" aria-live="polite"></div><div class="cc-chat-choices"><button type="button">Book a session</button><button type="button">Share feedback</button><button type="button">Find my IDs</button><button type="button">Contact a manager</button></div><form class="cc-chat-form"><input aria-label="Ask a question" placeholder="Type your question…" maxlength="300"><button type="submit">Send</button></form>';document.body.append(chat);
const log=chat.querySelector('.cc-chat-log');
function message(text,user=false){const node=document.createElement('div');node.className=`cc-chat-message${user?' is-user':''}`;node.textContent=text;log.append(node);log.scrollTop=log.scrollHeight}
function answer(question){const value=question.toLowerCase();if(/book|appointment|session|service/.test(value))return'Use Book a session to choose vehicle services and request a date. The team will email your booking reference and confirm the appointment.';if(/feedback|review|rate/.test(value))return'Open Share feedback after your job is complete. The Job ID and customer details are normally filled from the email link.';if(/job id|customer id|reference/.test(value))return'Your Job ID and Customer ID appear in CarCare emails and attached PDFs. Staff can also see them on the completion receipt.';if(/manager|human|complaint|problem|urgent/.test(value))return'Negative feedback enters the management dashboard. Severe or repeat concerns receive priority. For immediate safety concerns, stop driving and contact the service team directly.';if(/reply|email/.test(value))return'The dashboard records when CarCare sends an email and whether a customer reply has arrived. You can reply directly to a CarCare email.';return'I can help with bookings, feedback, Job IDs, Customer IDs, email replies and manager follow-up. Choose a topic below or ask in a short sentence.'}
message('Good day. How can I help you with CarCare?');chat.querySelector('.cc-chat-head button').addEventListener('click',()=>chat.hidden=true);launcher.querySelector('[data-chat-open]').addEventListener('click',()=>{chat.hidden=!chat.hidden;if(!chat.hidden)chat.querySelector('input').focus()});chat.querySelectorAll('.cc-chat-choices button').forEach(button=>button.addEventListener('click',()=>{message(button.textContent,true);message(answer(button.textContent))}));chat.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const input=event.currentTarget.querySelector('input'),value=input.value.trim();if(!value)return;message(value,true);message(answer(value));input.value=''});

const tours={
  '/carcare':[['.cc-hero-copy','CarCare overview','This project connects completed jobs, customer feedback, service recovery and public positive stories.'],['.cc-access-grid','Choose a workspace','Staff complete jobs, customers send feedback or book service, and managers review the dashboard.'],['#how-it-works','Feedback routing','The system reads each response, routes it and highlights severe or repeat concerns.']],
  '/carcare/complete':[['#staff','Staff job completion','Enter the customer, location and attending staff member here.'],['#job-form','Automatic references','Submitting creates the Job ID, reuses or creates the Customer ID and emails the feedback link.']],
  '/carcare/feedback':[['#feedback','Customer feedback','The visit details can arrive prefilled from the feedback-request email.'],['.cc-rating','Rating and comments','Choose a rating and describe the visit. Severe and repeat complaints receive extra attention.']],
  '/carcare/book':[['#booking','Session booking','Enter contact and vehicle details, then select every service required.'],['.cc-service-groups','Service catalogue','Choose one or more inspection, maintenance, repair, detailing or emergency options.'],['[name="preferred_date"]','Appointment preference','Request a date and time. The team confirms the final appointment separately.']],
  '/carcare/testimonials':[['#testimonials','Approved customer stories','Only positive feedback tagged Ready to post appears on this page. Personal email addresses and IDs stay private.']],
  '/carcare/admin':[['#metrics','Feedback overview','These totals summarize active feedback and cases that need action.'],['#booking-title','Booking and reply desk','Review appointment requests and see whether customer emails are awaiting a reply.'],['#queue','Case controls','Review AI drafts, send customer emails and update response, alert and publishing status.']]
};
let steps=tours[path]||tours['/carcare'],tourIndex=0,tourOverlay;
function endTour(){document.querySelector('.cc-tour-focus')?.classList.remove('cc-tour-focus');tourOverlay?.remove();tourOverlay=null}
function showStep(){endTour();const [selector,title,body]=steps[tourIndex],target=document.querySelector(selector);if(!target){tourIndex+=1;if(tourIndex<steps.length)showStep();return}target.classList.add('cc-tour-focus');target.scrollIntoView({behavior:'smooth',block:'center'});tourOverlay=document.createElement('div');tourOverlay.className='cc-tour';const card=document.createElement('div');card.className='cc-tour-card';card.innerHTML=`<small>STEP ${tourIndex+1} OF ${steps.length}</small><h2>${title}</h2><p>${body}</p><div class="cc-tour-actions"><button type="button" data-tour-close>Close</button><button type="button" data-tour-next>${tourIndex===steps.length-1?'Finish':'Next'}</button></div>`;tourOverlay.append(card);document.body.append(tourOverlay);requestAnimationFrame(()=>{const rect=target.getBoundingClientRect(),width=Math.min(410,innerWidth-28);card.style.left=`${Math.max(14,Math.min(innerWidth-width-14,rect.left))}px`;card.style.top=`${Math.max(14,Math.min(innerHeight-card.offsetHeight-14,rect.bottom+14))}px`});card.querySelector('[data-tour-close]').addEventListener('click',endTour);card.querySelector('[data-tour-next]').addEventListener('click',()=>{document.querySelector('.cc-tour-focus')?.classList.remove('cc-tour-focus');if(++tourIndex>=steps.length){endTour();localStorage.setItem(`carcare-tour:${path}`,'done');return}showStep()})}
launcher.querySelector('[data-tour-open]').addEventListener('click',()=>{tourIndex=0;showStep()});
if(!localStorage.getItem(`carcare-tour:${path}`)){const welcome=document.createElement('div');welcome.className='cc-tour-welcome';welcome.innerHTML='<button type="button" aria-label="Dismiss">×</button><strong>First time here?</strong><br>Use “Take a tour” for a short guide to this page.';document.body.append(welcome);welcome.querySelector('button').addEventListener('click',()=>{welcome.remove();localStorage.setItem(`carcare-tour:${path}`,'dismissed')});setTimeout(()=>welcome.remove(),9000)}
