import {designReadiness,safeProjectPrefill} from '../lib/resource-tools.mjs';
import {resourceBySlug} from '../lib/resource-catalog.mjs';
import {renderResourceAsset} from '../lib/resource-assets.mjs';
import {attribution,track} from '../project-management/analytics.mjs';

const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const resourceSlug=document.body.dataset.resourceSlug||'';
if(resourceSlug)track('resource_view',{resource_slug:resourceSlug,resource_scope:document.body.dataset.resourceScope||'shared'});

function downloadText(filename,text){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url);}
function resourceText(resource){return renderResourceAsset(resource)}

$$('[data-resource-claim]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const button=$('button[type="submit"]',form),status=$('[data-claim-status]',form),values=Object.fromEntries(new FormData(form));button.disabled=true;status.textContent='Preparing your resource…';track('resource_claim_started',{resource_slug:values.resourceSlug});try{const response=await fetch('/api/v1/resources/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,marketingConsent:values.marketingConsent==='on',attribution:attribution()})}),result=await response.json();if(!response.ok)throw new Error(result.message||'The resource could not be prepared.');const resource=resourceBySlug(values.resourceSlug),output=$('[data-claimed-resource]');output.hidden=false;output.innerHTML=`<h2>Your resource is ready.</h2><p>${esc(resource.outcome)}</p><div class="print-actions"><button class="button button-dark" type="button" data-download-asset>Download text version</button><a class="button" href="/start-a-project?${safeProjectPrefill({source_resource:resource.slug,project_type:values.projectType})}" data-start-project>Start a Project with this context</a></div>`;$('[data-download-asset]',output).addEventListener('click',()=>{downloadText(`ArkHimar_${resource.slug}_v${resource.version}.txt`,resourceText(resource));track('tool_printed_or_exported',{resource_slug:resource.slug,export_type:'txt'})});$('[data-start-project]',output).addEventListener('click',()=>track('start_project_cta_clicked',{resource_slug:resource.slug}));status.textContent=result.emailed?'Ready. A reference copy has also been emailed to you.':'Ready for immediate download.';track('resource_claim_completed',{resource_slug:resource.slug,delivery:'instant'})}catch(error){status.textContent=error.message}finally{button.disabled=false}}));

const assessment=$('[data-design-readiness]');if(assessment){let started=false;assessment.addEventListener('input',()=>{if(!started){track('tool_started',{tool_id:'design-readiness-assessment'});started=true}});assessment.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries($$('input[type="checkbox"]',assessment).map(input=>[input.name,input.checked])),result=designReadiness(values),output=$('[data-assessment-result]');output.hidden=false;output.innerHTML=`<p class="eyebrow">DIRECTIONAL RESULT</p><div class="result-score">${result.score}%</div><h2>${result.level}</h2><p>${result.completed} of ${result.total} preparation areas are currently in place.</p>${result.actions.length?`<h3>Recommended next actions</h3><ol class="result-actions">${result.actions.map(item=>`<li>${esc(item.action)}</li>`).join('')}</ol>`:'<p>Keep the evidence current and review assumptions with the appropriate professionals.</p>'}<p class="resource-disclaimer">A high score does not establish legal, statutory, technical or cost compliance.</p><div class="print-actions"><button class="button" type="button" data-print-result>Print result</button><a class="button button-dark" data-start-project href="/start-a-project?${safeProjectPrefill({source_resource:'design-readiness-assessment'})}">Discuss the next professional step</a><a class="button" data-use-in-pm href="/project-management/workflow-packs/project-initiation-pack">Continue with the PM initiation pack</a></div>`;$('[data-print-result]',output).addEventListener('click',()=>{track('tool_printed_or_exported',{tool_id:'design-readiness-assessment',export_type:'print'});print()});track('tool_completed',{tool_id:'design-readiness-assessment',score_band:result.score>=75?'75-100':result.score>=50?'50-74':'0-49'});output.scrollIntoView({behavior:'smooth',block:'start'})})}

const builder=$('[data-brief-builder]');if(builder){let started=false;builder.addEventListener('input',()=>{if(!started){track('tool_started',{tool_id:'project-brief-builder'});started=true}});builder.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(builder)),output=$('[data-brief-result]'),rows=[['Project type',values.projectType],['Purpose and intended outcome',values.purpose],['Spaces or functions needed',values.spaces],['Site information available',values.siteInformation],['Budget clarity',values.budgetClarity],['Timeline',values.timeline],['Decision-makers',values.decisionMakers]];output.hidden=false;output.innerHTML='<p class="eyebrow">DRAFT CLIENT BRIEF</p><h2>Review before sharing.</h2><dl>'+rows.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'Not yet defined')}</dd></div>`).join('')+'</dl><p class="resource-disclaimer">This draft remains in your browser. Review it before choosing to send any project information.</p><div class="print-actions"><button class="button" type="button" data-print-result>Print draft</button><a class="button button-dark" data-start-project href="/start-a-project?'+safeProjectPrefill({source_resource:'project-brief-builder',project_type:values.projectType})+'">Continue to Start a Project</a></div>';$('[data-print-result]',output).addEventListener('click',()=>{track('tool_printed_or_exported',{tool_id:'project-brief-builder',export_type:'print'});print()});track('tool_completed',{tool_id:'project-brief-builder'});output.scrollIntoView({behavior:'smooth',block:'start'})})}

$$('[data-use-in-pm]').forEach(link=>link.addEventListener('click',()=>{const slug=link.dataset.useInPm||resourceSlug,resource=resourceBySlug(slug);if(resource?.importable){sessionStorage.setItem('arkhimar.pm.pending-resource-import',JSON.stringify({slug:resource.slug,version:resource.version,title:resource.title,summary:resource.summary}));link.href='/pm/'}track('use_in_pm_clicked',{resource_slug:slug})}));
$$('[data-print-resource]').forEach(button=>button.addEventListener('click',()=>{track('tool_printed_or_exported',{resource_slug:button.dataset.printResource||resourceSlug,export_type:'print'});print()}));
