import {currentSession} from './backend.js';

const escapeHtml=(value='')=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let conversationId=null,lastAnswer=null,voiceProfile='professional-female',retaining=true,recognition=null;

async function aiRequest(path,{method='GET',body}={}){const session=await currentSession();if(!session)throw new Error('Your session expired. Sign in again.');const response=await fetch(path,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'ArkHimar Intelligence is unavailable');return result}

export function renderAi(project,cloud){
  return `<header class="page-heading ai-heading"><div><p>ARKHIMAR INTELLIGENCE</p><h1>AI Assistance</h1><span>${escapeHtml(project.code)} · grounded in the current authorized project record</span></div><span class="ai-health" data-ai-health><i></i> Checking provider</span></header>
  <section class="ai-context-strip"><span><small>CONTEXT</small>${escapeHtml(project.title)}</span><span><small>SCOPE</small>This project</span><span><small>ROLE</small>${escapeHtml(cloud.role.replaceAll('_',' '))}</span><span><small>PRIVACY</small><label><input type="checkbox" data-ai-retain checked> Retain history</label></span></section>
  <div class="ai-workspace-grid"><section class="panel ai-main"><div class="section-title"><div><p class="eyebrow">ASK ARKHIMAR</p><h2>Turn project intent into governed work.</h2></div><span class="status-chip">Preview before action</span></div>
  <div class="ai-modes" role="group" aria-label="AI specialist"><button class="active" type="button" data-ai-mode="PM Copilot">PM Copilot</button>${['Planning','Risk','Cost','Construction','Document','Meeting','Executive'].map(x=>`<button type="button" data-ai-mode="${x}">${x}</button>`).join('')}</div>
  <div class="ai-transcript" data-ai-transcript aria-live="polite"><article class="ai-message assistant"><small>ARKHIMAR INTELLIGENCE</small><p>Ask about this project, request a draft, or describe work to organize. Important answers cite the project record; governed actions always require approval.</p></article></div>
  <form class="ai-composer" data-ai-form><label class="sr-only" for="ai-prompt">Ask ArkHimar</label><textarea id="ai-prompt" name="message" rows="3" maxlength="12000" required placeholder="For example: What is holding this project back, and what should I do next?"></textarea><div><button class="secondary" type="button" data-ai-mic aria-pressed="false">● Push to talk</button><label>Voice <select data-ai-voice><option value="professional-female">Professional Female</option><option value="professional-male">Professional Male</option><option value="mature-female">Mature Female</option><option value="mature-male">Mature Male</option><option value="warm-guide">Warm Guide</option><option value="site-coordinator">Calm Site Coordinator</option></select></label><button class="primary" type="submit">Ask ArkHimar →</button></div><p class="status" data-ai-status></p></form>
  <div class="ai-actions" data-ai-actions hidden><p class="eyebrow">PROPOSED ACTIONS</p><div data-ai-action-list></div></div></section>
  <aside class="ai-side"><section class="panel"><p class="eyebrow">CONTEXT CONTROL</p><h3>Sources and confidence</h3><div data-ai-sources><p class="helper">Sources used in the latest answer will appear here.</p></div></section><section class="panel"><p class="eyebrow">SAFE AUTOMATIONS</p><h3>Approval-first recipes</h3><div data-ai-automations><p class="helper">Loading automation templates…</p></div></section><section class="panel ai-safety"><p class="eyebrow">AUTHORITY BOUNDARY</p><p>ArkHimar can read and draft. Baselines, approvals, external communications, contracts and financial commitments remain human-controlled.</p></section></aside></div>`;
}

function appendMessage(root,role,text,meta=''){const article=document.createElement('article');article.className=`ai-message ${role}`;article.innerHTML=`<small>${role==='user'?'YOU':'ARKHIMAR INTELLIGENCE'}${meta?` · ${escapeHtml(meta)}`:''}</small><p>${escapeHtml(text).replaceAll('\n','<br>')}</p>`;root.append(article);root.scrollTop=root.scrollHeight}
function renderSources(result){const target=document.querySelector('[data-ai-sources]');target.innerHTML=`<p><strong>${escapeHtml(result.confidence||'medium')} confidence</strong></p>${(result.citations||[]).map(x=>`<article class="ai-source"><strong>${escapeHtml(x.label)}</strong><small>${escapeHtml(x.entityType)} · version ${escapeHtml(x.version)}</small></article>`).join('')||'<p class="helper">No project source was available.</p>'}`}
function renderActions(result){const box=document.querySelector('[data-ai-actions]'),list=document.querySelector('[data-ai-action-list]'),actions=result.proposedActions||[];box.hidden=!actions.length;list.innerHTML=actions.map(x=>`<article><div><strong>${escapeHtml(x.label)}</strong><small>${escapeHtml(x.riskLevel)} · ${escapeHtml(x.authorization?.reason||'ready')}</small></div><button type="button" disabled>${x.authorization?.requiresApproval?'Approval required':x.authorization?.allowed?'Review':'Not permitted'}</button></article>`).join('')}

export async function bindAi(project,cloud,notify){
  const form=document.querySelector('[data-ai-form]');if(!form)return;
  let mode='PM Copilot';document.querySelectorAll('[data-ai-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.aiMode;document.querySelectorAll('[data-ai-mode]').forEach(x=>x.classList.toggle('active',x===button))}));
  document.querySelector('[data-ai-retain]').addEventListener('change',event=>retaining=event.target.checked);
  document.querySelector('[data-ai-voice]').addEventListener('change',event=>voiceProfile=event.target.value);
  form.addEventListener('submit',async event=>{event.preventDefault();const input=form.elements.message,message=input.value.trim(),status=document.querySelector('[data-ai-status]'),button=form.querySelector('[type="submit"]'),transcript=document.querySelector('[data-ai-transcript]');if(!message)return;appendMessage(transcript,'user',message);input.value='';button.disabled=true;status.textContent='Reading authorized project context…';try{const result=await aiRequest('/api/v1/ai/chat',{method:'POST',body:{workspaceId:cloud.workspace.id,projectId:project.id,conversationId,message,scope:'project',mode,retain:retaining}});conversationId=result.conversationId;lastAnswer=result;appendMessage(transcript,'assistant',result.answer,`${result.route} · ${result.confidence} confidence`);renderSources(result);renderActions(result);status.textContent=result.provider==='grounded-fallback'?'Grounded fallback active. Live model reasoning is not configured.':'Answer complete.'}catch(error){appendMessage(transcript,'assistant',`I could not complete that request: ${error.message}`,'failed');status.textContent='Request failed.'}finally{button.disabled=false;input.focus()}});
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition,mic=document.querySelector('[data-ai-mic]');if(!SpeechRecognition){mic.disabled=true;mic.textContent='Voice unavailable'}else{mic.addEventListener('click',()=>{if(recognition){recognition.stop();return}recognition=new SpeechRecognition();recognition.lang='en-NG';recognition.interimResults=true;recognition.onstart=()=>{mic.setAttribute('aria-pressed','true');mic.textContent='■ Stop listening'};recognition.onresult=event=>{form.elements.message.value=[...event.results].map(x=>x[0].transcript).join('')};recognition.onerror=event=>notify('Voice input unavailable',event.error);recognition.onend=()=>{recognition=null;mic.setAttribute('aria-pressed','false');mic.textContent='● Push to talk'};recognition.start()})}
  try{const health=await aiRequest(`/api/v1/ai/context?workspaceId=${encodeURIComponent(cloud.workspace.id)}&projectId=${encodeURIComponent(project.id)}`),badge=document.querySelector('[data-ai-health]');badge.classList.toggle('degraded',health.health.assistant!=='available');badge.innerHTML=`<i></i> ${health.health.assistant==='available'?'AI available':'Grounded fallback'}`;const automations=await aiRequest(`/api/v1/ai/automations?workspaceId=${encodeURIComponent(cloud.workspace.id)}&projectId=${encodeURIComponent(project.id)}`);document.querySelector('[data-ai-automations]').innerHTML=automations.automations.map(x=>`<label class="automation-row"><input type="checkbox" data-ai-automation="${escapeHtml(x.id)}" ${x.enabled?'checked':''} ${!['owner','admin','project_manager'].includes(cloud.role)?'disabled':''}><span><strong>${escapeHtml(x.name)}</strong><small>Human approval required</small></span></label>`).join('');document.querySelectorAll('[data-ai-automation]').forEach(input=>input.addEventListener('change',async()=>{input.disabled=true;try{await aiRequest('/api/v1/ai/automations',{method:'POST',body:{workspaceId:cloud.workspace.id,projectId:project.id,templateId:input.dataset.aiAutomation,enabled:input.checked,config:{}}});notify('Automation updated',input.checked?'The approval-first recipe is active.':'The recipe is paused.')}catch(error){input.checked=!input.checked;notify('Automation not updated',error.message)}finally{input.disabled=false}}))}catch(error){document.querySelector('[data-ai-health]').innerHTML='<i></i> Unavailable';document.querySelector('[data-ai-health]').classList.add('degraded');document.querySelector('[data-ai-automations]').innerHTML=`<p class="helper">${escapeHtml(error.message)}</p>`}
}

export function speakLastAnswer(){if(!lastAnswer||!speechSynthesis)return;const utterance=new SpeechSynthesisUtterance(lastAnswer.answer);utterance.rate=1;utterance.lang=voiceProfile==='site-coordinator'?'en-NG':'en-GB';speechSynthesis.cancel();speechSynthesis.speak(utterance)}
