import {createClient} from '@supabase/supabase-js';

const config=globalThis.__ARKHIMAR_CONFIG__||{};
export const backendConfigured=Boolean(config.supabaseUrl&&config.supabaseAnonKey);
export const supabase=backendConfigured?createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;

function publicProject(project){const {_version,_documents,_controlledDocuments,...data}=project;return data}
export async function currentSession(){if(!supabase)return null;const {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;if(!session)return null;const {data:{user},error:userError}=await supabase.auth.getUser();if(userError)return null;return{...session,user}}
export async function loadWorkspaceContext(){
  if(!backendConfigured)return{configured:false,session:null,workspace:null,role:null,projects:[]};
  const session=await currentSession();if(!session)return{configured:true,session:null,workspace:null,role:null,projects:[]};
  const {data:memberships,error:memberError}=await supabase.from('workspace_members').select('workspace_id,role,workspaces(id,name,slug)').order('joined_at',{ascending:true}).limit(1);if(memberError)throw new Error(memberError.code==='42501'?'Your account is verified, but authenticated database access has not been activated yet. Apply the latest ArkHimar database migration and retry.':memberError.message);
  const membership=memberships?.[0];if(!membership)return{configured:true,session,workspace:null,role:null,projects:[]};
  const {data:rows,error}=await supabase.from('projects').select('id,title,code,data,version,created_at,updated_at').eq('workspace_id',membership.workspace_id).is('archived_at',null).order('updated_at',{ascending:false});if(error)throw error;
  return{configured:true,session,workspace:membership.workspaces,role:membership.role,projects:(rows||[]).map(row=>({...row.data,id:row.id,title:row.title,code:row.code,_version:row.version}))};
}
export async function bootstrapWorkspace(name){const {data,error}=await supabase.rpc('bootstrap_workspace',{workspace_name:name});if(error)throw error;return data}
export async function createProject(workspaceId,project,userId){const payload=publicProject(project);const {data,error}=await supabase.from('projects').insert({id:project.id,workspace_id:workspaceId,title:project.title,code:project.code,data:payload,created_by:userId}).select('id,title,code,data,version').single();if(error)throw error;return{...data.data,id:data.id,title:data.title,code:data.code,_version:data.version}}
export async function updateProject(project){const payload=publicProject(project);const {data,error}=await supabase.from('projects').update({title:project.title,code:project.code,data:payload}).eq('id',project.id).eq('version',project._version||1).select('version').maybeSingle();if(error)throw error;if(!data)throw new Error('This project changed in another session. Reload before saving again.');project._version=data.version;return project}
export async function listDocuments(projectId){const {data,error}=await supabase.from('project_documents').select('id,filename,content_type,size_bytes,created_at,storage_path').eq('project_id',projectId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function listControlledDocuments(projectId){
  const {data:documents,error}=await supabase.from('controlled_documents').select('*').eq('project_id',projectId).order('updated_at',{ascending:false});if(error)throw error;
  const ids=(documents||[]).map(document=>document.id);if(!ids.length)return[];
  const [{data:versions,error:versionError},{data:shares,error:shareError}]=await Promise.all([supabase.from('controlled_document_versions').select('*').in('document_id',ids).order('version',{ascending:false}),canReadDocumentShares()?supabase.from('controlled_document_shares').select('id,document_id,version,format,expires_at,max_downloads,download_count,revoked_at,created_at').in('document_id',ids).order('created_at',{ascending:false}):Promise.resolve({data:[],error:null})]);if(versionError)throw versionError;if(shareError)throw shareError;
  return documents.map(document=>({...document,versions:(versions||[]).filter(version=>version.document_id===document.id),shares:(shares||[]).filter(share=>share.document_id===document.id)}));
}
function canReadDocumentShares(){return Boolean(supabase)}
export async function createControlledDocument(projectId,values){const {data,error}=await supabase.rpc('create_controlled_document',{target_project:projectId,document_id_code:values.document_code,document_type:values.artifact_type,document_title:values.title,document_owner:values.owner_name||'',document_confidentiality:values.confidentiality||'Internal',document_tags:(values.tags||'').split(',').map(tag=>tag.trim()).filter(Boolean),document_content:{summary:values.summary||''},revision_note:values.revision_notes||''});if(error)throw error;return data}
export async function transitionControlledDocument(documentId,status){const {error}=await supabase.rpc('transition_controlled_document',{target_document:documentId,next_status:status});if(error)throw error}
export async function reviseControlledDocument(documentId,summary,revisionNotes){const {data,error}=await supabase.rpc('revise_controlled_document',{target_document:documentId,document_content:{summary},revision_note:revisionNotes});if(error)throw error;return data}
async function documentRequest(path,payload,method='POST'){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch(path,{method,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.message||result.error||'Document request failed')}return response}
export async function downloadControlledDocument(documentId,version,format){const response=await documentRequest('/api/v1/documents/export',{documentId,version,format}),blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',filename=disposition.match(/filename="([^"]+)"/)?.[1]||`ArkHimar-document.${format}`;return{blob,filename}}
export async function createDocumentShare(documentId,version,format,expiresInHours=168,maxDownloads=10){const response=await documentRequest('/api/v1/documents/shares',{documentId,version,format,expiresInHours,maxDownloads});return response.json()}
export async function revokeDocumentShare(documentId,shareId){const response=await documentRequest('/api/v1/documents/shares',{documentId,shareId},'DELETE');return response.json()}
export async function importResourceDraft(projectId,resource){const {data,error}=await supabase.rpc('import_resource_draft',{target_project:projectId,source_slug:resource.slug,source_version:resource.version});if(error)throw error;return data}
export async function uploadDocument({workspaceId,projectId,userId,file}){const safe=file.name.normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-120),path=`${workspaceId}/${projectId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from('project-documents').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await supabase.from('project_documents').insert({workspace_id:workspaceId,project_id:projectId,storage_path:path,filename:file.name,content_type:file.type,size_bytes:file.size,uploaded_by:userId}).select().single();if(error){await supabase.storage.from('project-documents').remove([path]);throw error}return data}
export async function signedDocumentUrl(path){const {data,error}=await supabase.storage.from('project-documents').createSignedUrl(path,60);if(error)throw error;return data.signedUrl}
export async function loadWorkspaceTools(workspaceId,role){
  const canAdmin=['owner','admin'].includes(role),canManage=canAdmin||role==='project_manager';
  const requests=[
    supabase.from('workspace_brand_settings').select('*').eq('workspace_id',workspaceId).maybeSingle(),
    supabase.from('message_templates').select('*').eq('workspace_id',workspaceId).is('archived_at',null).order('updated_at',{ascending:false}),
    canManage?supabase.from('outbound_messages').select('id,subject,recipients,status,provider_message_id,error_message,created_at,sent_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(25):Promise.resolve({data:[],error:null}),
    canManage?supabase.from('form_submissions').select('id,form_id,submitter_name,submitter_email,message,fields,received_at').eq('workspace_id',workspaceId).order('received_at',{ascending:false}).limit(25):Promise.resolve({data:[],error:null}),
    supabase.from('project_documents').select('id,project_id,filename,size_bytes').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(100)
  ];
  const [brand,templates,messages,submissions,documents]=await Promise.all(requests);
  for(const result of [brand,templates,messages,submissions,documents])if(result.error)throw result.error;
  let apiKeys=[];
  if(canAdmin){const {data,error}=await supabase.rpc('list_workspace_api_keys',{target_workspace:workspaceId});if(error)throw error;apiKeys=data||[]}
  if(brand.data){for(const [pathField,urlField] of [['logo_path','logo_url'],['letterhead_path','letterhead_url']])if(brand.data[pathField]){const {data}=await supabase.storage.from('workspace-brand-assets').createSignedUrl(brand.data[pathField],300);brand.data[urlField]=data?.signedUrl||''}}
  return{brand:brand.data,templates:templates.data||[],messages:messages.data||[],submissions:submissions.data||[],documents:documents.data||[],apiKeys,revealedKey:null};
}
export async function saveWorkspaceBrand(workspaceId,userId,values){const row={workspace_id:workspaceId,sender_name:values.sender_name,reply_to:values.reply_to||null,primary_color:values.primary_color,accent_color:values.accent_color,background_color:values.background_color,footer_text:values.footer_text,updated_by:userId,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('workspace_brand_settings').upsert(row).select().single();if(error)throw error;return data}
export async function uploadBrandAsset({workspaceId,userId,file,kind}){const safe=file.name.normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-100),path=`${workspaceId}/${kind}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('workspace-brand-assets').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const field=kind==='logo'?'logo_path':'letterhead_path',{data:current}=await supabase.from('workspace_brand_settings').select('*').eq('workspace_id',workspaceId).maybeSingle(),values={workspace_id:workspaceId,sender_name:current?.sender_name||'ArkHimar PM',reply_to:current?.reply_to||null,primary_color:current?.primary_color||'#191916',accent_color:current?.accent_color||'#B86B42',background_color:current?.background_color||'#F5F3ED',footer_text:current?.footer_text||'Generated with ArkHimar PM',logo_path:current?.logo_path||null,letterhead_path:current?.letterhead_path||null,updated_by:userId,updated_at:new Date().toISOString(),[field]:path};const {data,error:updateError}=await supabase.from('workspace_brand_settings').upsert(values).select().single();if(updateError){await supabase.storage.from('workspace-brand-assets').remove([path]);throw updateError}return data}
export async function saveMessageTemplate(workspaceId,userId,template){const values={workspace_id:workspaceId,name:template.name,kind:template.kind,subject:template.subject,blocks:template.blocks,created_by:userId};const query=template.id?supabase.from('message_templates').update({...values,version:(template.version||1)+1,updated_at:new Date().toISOString()}).eq('id',template.id):supabase.from('message_templates').insert(values);const {data,error}=await query.select().single();if(error)throw error;return data}
export async function createWorkspaceApiKey(workspaceId,label,scopes=['forms:submit']){const {data,error}=await supabase.rpc('create_workspace_api_key',{target_workspace:workspaceId,key_label:label,key_scopes:scopes});if(error)throw error;return data?.[0]}
export async function revokeWorkspaceApiKey(id){const {error}=await supabase.rpc('revoke_workspace_api_key',{target_key:id});if(error)throw error}
export async function sendWorkspaceMessage(payload){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/messages/send',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Message delivery failed');return result}
export async function loadWorkspaceTeam(workspaceId,role){const {data:members,error}=await supabase.from('workspace_members').select('user_id,role,joined_at').eq('workspace_id',workspaceId).order('joined_at');if(error)throw error;const ids=(members||[]).map(member=>member.user_id);let profiles=[];if(ids.length){const result=await supabase.from('profiles').select('id,display_name').in('id',ids);if(result.error)throw result.error;profiles=result.data||[]}const names=new Map(profiles.map(profile=>[profile.id,profile.display_name]));let invitations=[];if(['owner','admin'].includes(role)){const result=await supabase.from('workspace_invitations').select('id,email,role,delivery_status,expires_at,accepted_at,revoked_at,created_at').eq('workspace_id',workspaceId).is('accepted_at',null).is('revoked_at',null).order('created_at',{ascending:false});if(result.error)throw result.error;invitations=result.data||[]}return{members:(members||[]).map(member=>({...member,display_name:names.get(member.user_id)||''})),invitations}}
export async function inviteWorkspaceMember(payload){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/workspace/invitations',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Invitation could not be sent');return result}
export async function revokeWorkspaceInvitation(workspaceId,invitationId){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/workspace/invitations',{method:'DELETE',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,invitationId})}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Invitation could not be revoked');return result}
export async function updateWorkspaceMemberRole(workspaceId,userId,role){const {data,error}=await supabase.from('workspace_members').update({role}).eq('workspace_id',workspaceId).eq('user_id',userId).select('user_id,role').maybeSingle();if(error)throw error;if(!data)throw new Error('Your role does not permit this membership change.');return data}
export async function removeWorkspaceMember(workspaceId,userId){const {data,error}=await supabase.from('workspace_members').delete().eq('workspace_id',workspaceId).eq('user_id',userId).select('user_id').maybeSingle();if(error)throw error;if(!data)throw new Error('Your role does not permit removing this member.');return data}
export async function mfaRequirement(){const [{data:factors,error:factorError},{data:assurance,error:assuranceError}]=await Promise.all([supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);if(factorError)throw factorError;if(assuranceError)throw assuranceError;const factor=factors.totp?.[0]||null;return{factor,currentLevel:assurance.currentLevel,nextLevel:assurance.nextLevel,required:Boolean(factor&&assurance.currentLevel==='aal1'&&assurance.nextLevel==='aal2')}}
export async function verifyMfaCode(factorId,code){const {data,error}=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(error)throw error;return data}
export async function signOut(){if(supabase)await supabase.auth.signOut({scope:'local'});location.replace('/pm/login/')}
