import {createClient} from '@supabase/supabase-js';

const config=globalThis.__ARKHIMAR_CONFIG__||{};
export const backendConfigured=Boolean(config.supabaseUrl&&config.supabaseAnonKey);
export const supabase=backendConfigured?createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;

function publicProject(project){const data=Object.fromEntries(Object.entries(project).filter(([key])=>!key.startsWith('_')&&!['execution','reports'].includes(key)));for(const section of ['business','charter','planning'])if(data[section])data[section]=Object.fromEntries(Object.entries(data[section]).filter(([key])=>!key.startsWith('_')));return data}
const initiationStatus=status=>({draft:'Draft',in_review:'Submitted',changes_requested:'Changes Requested',approved:'Approved',archived:'Archived'}[status]||'Draft');
async function loadInitiationForProjects(projectIds){
  if(!projectIds.length)return new Map();
  const [{data:cases,error:caseError},{data:charters,error:charterError}]=await Promise.all([supabase.from('business_cases').select('id,project_id,status,current_version').in('project_id',projectIds),supabase.from('project_charters').select('id,project_id,status,current_version').in('project_id',projectIds)]);if(caseError)throw caseError;if(charterError)throw charterError;
  const caseIds=(cases||[]).map(item=>item.id),charterIds=(charters||[]).map(item=>item.id);
  const [caseVersions,charterVersions]=await Promise.all([caseIds.length?supabase.from('business_case_versions').select('id,business_case_id,version,status,content,submitted_at,approved_at').in('business_case_id',caseIds):Promise.resolve({data:[],error:null}),charterIds.length?supabase.from('project_charter_versions').select('id,charter_id,version,status,content,submitted_at,approved_at').in('charter_id',charterIds):Promise.resolve({data:[],error:null})]);if(caseVersions.error)throw caseVersions.error;if(charterVersions.error)throw charterVersions.error;
  const currentCaseVersions=(caseVersions.data||[]).filter(version=>(cases||[]).some(item=>item.id===version.business_case_id&&item.current_version===version.version)),currentCharterVersions=(charterVersions.data||[]).filter(version=>(charters||[]).some(item=>item.id===version.charter_id&&item.current_version===version.version)),caseVersionIds=currentCaseVersions.map(item=>item.id);
  const [options,caseDecisions,charterDecisions]=await Promise.all([caseVersionIds.length?supabase.from('business_case_options').select('*').in('business_case_version_id',caseVersionIds).order('sort_order'):Promise.resolve({data:[],error:null}),caseIds.length?supabase.from('business_case_decisions').select('business_case_id,version,decision,comments,decided_at').in('business_case_id',caseIds).order('decided_at',{ascending:false}):Promise.resolve({data:[],error:null}),charterIds.length?supabase.from('project_charter_decisions').select('charter_id,version,decision,comments,decided_at').in('charter_id',charterIds).order('decided_at',{ascending:false}):Promise.resolve({data:[],error:null})]);for(const result of [options,caseDecisions,charterDecisions])if(result.error)throw result.error;
  const result=new Map(projectIds.map(id=>[id,{}]));
  for(const item of cases||[]){const version=currentCaseVersions.find(value=>value.business_case_id===item.id);if(!version)continue;result.get(item.project_id).business={...version.content,options:(options.data||[]).filter(option=>option.business_case_version_id===version.id).map(option=>({id:option.id,title:option.title,description:option.description,benefits:option.benefits,drawbacks:option.drawbacks,riskSummary:option.risk_summary,estimatedCost:Number(option.estimated_cost),durationMonths:Number(option.estimated_duration_months),scores:option.criteria_scores,weightedScore:Number(option.weighted_score),sortOrder:option.sort_order})),status:initiationStatus(item.status),version:item.current_version,_decisions:(caseDecisions.data||[]).filter(decision=>decision.business_case_id===item.id)};}
  for(const item of charters||[]){const version=currentCharterVersions.find(value=>value.charter_id===item.id);if(!version)continue;result.get(item.project_id).charter={...version.content,status:initiationStatus(item.status),version:item.current_version,approvedSnapshot:item.status==='approved'?{version:item.current_version,approvedAt:version.approved_at}:null,_decisions:(charterDecisions.data||[]).filter(decision=>decision.charter_id===item.id)};}
  return result;
}
export async function loadProjectInitiation(projectId){return(await loadInitiationForProjects([projectId])).get(projectId)||{}}
const planningStatus=status=>({draft:'Draft',baselined:'Baselined',archived:'Archived'}[status]||'Draft');
async function loadPlanningForProjects(projectIds){
  if(!projectIds.length)return new Map();
  const {data:sets,error}=await supabase.from('core_planning_sets').select('id,project_id,status,current_version').in('project_id',projectIds);if(error)throw error;
  const ids=(sets||[]).map(item=>item.id);if(!ids.length)return new Map();
  const {data:versions,error:versionError}=await supabase.from('core_planning_versions').select('id,planning_set_id,version,status,master_plan,scope_statement,subsidiary_plans,approved_at').in('planning_set_id',ids);if(versionError)throw versionError;
  const current=(versions||[]).filter(version=>(sets||[]).some(set=>set.id===version.planning_set_id&&set.current_version===version.version)),versionIds=current.map(item=>item.id);
  const [requirements,wbs,baselines]=await Promise.all([versionIds.length?supabase.from('requirements').select('*').in('planning_version_id',versionIds).order('requirement_code'):Promise.resolve({data:[],error:null}),versionIds.length?supabase.from('wbs_nodes').select('*').in('planning_version_id',versionIds).order('sort_order'):Promise.resolve({data:[],error:null}),supabase.from('scope_baselines').select('id,planning_set_id,version,name,status,approved_at,change_request_id').in('planning_set_id',ids).order('version',{ascending:false})]);for(const result of [requirements,wbs,baselines])if(result.error)throw result.error;
  const reqIds=(requirements.data||[]).map(item=>item.id),traces=reqIds.length?await supabase.from('requirement_traces').select('*').in('requirement_id',reqIds):{data:[],error:null};if(traces.error)throw traces.error;
  const result=new Map();for(const set of sets||[]){const version=current.find(item=>item.planning_set_id===set.id);if(!version)continue;const req=(requirements.data||[]).filter(item=>item.planning_version_id===version.id).map(item=>{const trace=(traces.data||[]).find(value=>value.requirement_id===item.id)||{};return{id:item.id,code:item.requirement_code,description:item.description,category:item.category,source:item.source,owner:item.owner_name,stakeholder:item.stakeholder,priority:item.priority,acceptanceCriteria:item.acceptance_criteria,rationale:item.rationale,status:item.status,targetRelease:item.target_release,verificationMethod:item.verification_method,validationMethod:item.validation_method,deliverable:item.deliverable_ref,wbs:item.wbs_ref,evidence:item.evidence_ref,changeHistory:item.change_history,objective:trace.strategic_objective||'',benefit:trace.benefit||'',activity:trace.activity_ref||'',traceStatus:trace.status||'Untraced'}});const nodes=(wbs.data||[]).filter(item=>item.planning_version_id===version.id).map(item=>({id:item.id,key:item.node_key,parentKey:item.parent_key||'',outline:item.outline_number,sortOrder:item.sort_order,type:item.node_type,name:item.name,owner:item.owner_name,effort:Number(item.estimated_effort),cost:Number(item.estimated_cost),requirements:item.linked_requirements,deliverables:item.linked_deliverables,dictionary:item.dictionary||{}}));const history=(baselines.data||[]).filter(item=>item.planning_set_id===set.id);result.set(set.project_id,{...version.scope_statement,...version.master_plan,subsidiaryPlans:version.subsidiary_plans||[],requirements:req,wbs:nodes,status:planningStatus(set.status),version:set.current_version,baseline:history[0]?{...history[0],approvedAt:history[0].approved_at}:null,_baselines:history});}return result;
}
export async function loadProjectPlanning(projectId){return(await loadPlanningForProjects([projectId])).get(projectId)||{}}
async function loadDeliveryForProjects(projectIds){
  if(!projectIds.length)return new Map();const [scheduleSets,costSets]=await Promise.all([supabase.from('schedule_control_sets').select('id,project_id,status,current_version').in('project_id',projectIds),supabase.from('cost_control_sets').select('id,project_id,status,current_version').in('project_id',projectIds)]);if(scheduleSets.error)throw scheduleSets.error;if(costSets.error)throw costSets.error;
  const scheduleIds=(scheduleSets.data||[]).map(x=>x.id),costIds=(costSets.data||[]).map(x=>x.id);const [scheduleVersions,costVersions,scheduleBaselines,costBaselines]=await Promise.all([scheduleIds.length?supabase.from('schedule_versions').select('*').in('schedule_set_id',scheduleIds):Promise.resolve({data:[],error:null}),costIds.length?supabase.from('cost_versions').select('*').in('cost_set_id',costIds):Promise.resolve({data:[],error:null}),scheduleIds.length?supabase.from('schedule_baselines').select('id,schedule_set_id,version,name,status,snapshot,approved_at,change_request_id').in('schedule_set_id',scheduleIds).order('version',{ascending:false}):Promise.resolve({data:[],error:null}),costIds.length?supabase.from('cost_baselines').select('id,cost_set_id,version,name,status,snapshot,approved_at,change_request_id').in('cost_set_id',costIds).order('version',{ascending:false}):Promise.resolve({data:[],error:null})]);for(const result of [scheduleVersions,costVersions,scheduleBaselines,costBaselines])if(result.error)throw result.error;
  const currentSchedules=(scheduleVersions.data||[]).filter(v=>(scheduleSets.data||[]).some(s=>s.id===v.schedule_set_id&&s.current_version===v.version)),currentCosts=(costVersions.data||[]).filter(v=>(costSets.data||[]).some(s=>s.id===v.cost_set_id&&s.current_version===v.version)),scheduleVersionIds=currentSchedules.map(x=>x.id),costVersionIds=currentCosts.map(x=>x.id);
  const [tasks,dependencies,costItems,cashFlow]=await Promise.all([scheduleVersionIds.length?supabase.from('schedule_tasks').select('*').in('schedule_version_id',scheduleVersionIds).order('sort_order'):Promise.resolve({data:[],error:null}),scheduleVersionIds.length?supabase.from('schedule_dependencies').select('*').in('schedule_version_id',scheduleVersionIds):Promise.resolve({data:[],error:null}),costVersionIds.length?supabase.from('cost_items').select('*').in('cost_version_id',costVersionIds).order('sort_order'):Promise.resolve({data:[],error:null}),costVersionIds.length?supabase.from('cash_flow_entries').select('*').in('cost_version_id',costVersionIds).order('period_date'):Promise.resolve({data:[],error:null})]);for(const result of [tasks,dependencies,costItems,cashFlow])if(result.error)throw result.error;
  const result=new Map(projectIds.map(id=>[id,{}]));for(const set of scheduleSets.data||[]){const v=currentSchedules.find(x=>x.schedule_set_id===set.id);if(!v)continue;const history=(scheduleBaselines.data||[]).filter(x=>x.schedule_set_id===set.id),mappedTasks=(tasks.data||[]).filter(x=>x.schedule_version_id===v.id).map(x=>({id:x.id,code:x.activity_code,wbs:x.wbs_ref,name:x.name,description:x.description,type:x.activity_type,milestone:x.milestone,duration:Number(x.duration),effort:Number(x.effort),plannedStart:x.planned_start||'',plannedFinish:x.planned_finish||'',actualStart:x.actual_start||'',actualFinish:x.actual_finish||'',remainingDuration:Number(x.remaining_duration),percentComplete:Number(x.percent_complete),owner:x.owner_name,resources:x.assigned_resources,calendar:x.calendar_ref,constraints:x.constraints,priority:x.priority,status:x.status,notes:x.notes,costAccount:x.cost_account_ref,sortOrder:x.sort_order}));result.get(set.project_id).schedule={...v.settings,calendar:v.calendar,tasks:mappedTasks,dependencies:(dependencies.data||[]).filter(x=>x.schedule_version_id===v.id).map(x=>({id:x.id,from:x.predecessor_code,to:x.successor_code,type:x.dependency_type,lag:Number(x.lag)})),status:set.status==='baselined'?'Baselined':'Draft',version:set.current_version,baseline:history[0]?{...history[0],approvedAt:history[0].approved_at}:null,_baselines:history};}
  for(const set of costSets.data||[]){const v=currentCosts.find(x=>x.cost_set_id===set.id);if(!v)continue;const history=(costBaselines.data||[]).filter(x=>x.cost_set_id===set.id);result.get(set.project_id).cost={...v.settings,items:(costItems.data||[]).filter(x=>x.cost_version_id===v.id).map(x=>({id:x.id,code:x.cost_code,account:x.cost_account,wbs:x.wbs_ref,activity:x.activity_ref,description:x.description,vendor:x.vendor,costType:x.cost_type,classification:x.classification,recordType:x.record_type,amount:Number(x.amount),tax:Number(x.tax_amount),currency:x.currency,dueDate:x.due_date||'',invoiceStatus:x.invoice_status,sortOrder:x.sort_order})),cashFlow:(cashFlow.data||[]).filter(x=>x.cost_version_id===v.id).map(x=>({id:x.id,date:x.period_date,planned:Number(x.planned),earned:Number(x.earned),actual:Number(x.actual),forecast:Number(x.forecast),milestone:x.payment_milestone,invoiceStatus:x.invoice_status})),status:set.status==='baselined'?'Baselined':'Draft',version:set.current_version,baseline:history[0]?{...history[0],approvedAt:history[0].approved_at}:null,_baselines:history};}return result;
}
export async function loadProjectDelivery(projectId){return(await loadDeliveryForProjects([projectId])).get(projectId)||{}}
async function loadControlsForProjects(projectIds){
  if(!projectIds.length)return new Map();const {data:sets,error}=await supabase.from('project_control_sets').select('*').in('project_id',projectIds);if(error)throw error;const ids=(sets||[]).map(x=>x.id);
  const [risks,issues,stakeholders,engagements,changes,history]=await Promise.all([ids.length?supabase.from('project_risks').select('*').in('control_set_id',ids).order('sort_order'):Promise.resolve({data:[],error:null}),ids.length?supabase.from('project_issues').select('*').in('control_set_id',ids).order('sort_order'):Promise.resolve({data:[],error:null}),ids.length?supabase.from('project_stakeholders').select('*,stakeholder_private_notes(note)').in('control_set_id',ids).order('sort_order'):Promise.resolve({data:[],error:null}),ids.length?supabase.from('stakeholder_engagement_actions').select('*').in('control_set_id',ids).order('due_date'):Promise.resolve({data:[],error:null}),supabase.from('change_requests').select('*').in('project_id',projectIds).order('created_at',{ascending:false}),supabase.from('change_request_history').select('*').in('project_id',projectIds).order('created_at',{ascending:false})]);for(const result of [risks,issues,stakeholders,engagements,changes,history])if(result.error)throw result.error;
  const result=new Map();for(const set of sets||[]){result.set(set.project_id,{riskPlan:set.risk_plan||{},version:set.current_version,risks:(risks.data||[]).filter(x=>x.control_set_id===set.id).map(x=>({id:x.id,code:x.risk_code,type:x.risk_type,cause:x.cause,event:x.event,impact:x.impact,category:x.category,objective:x.affected_objective,probability:Number(x.probability),impactScore:Number(x.impact_score),impactDimensions:x.impact_dimensions||{},proximity:x.proximity,urgency:x.urgency,detectability:x.detectability,owner:x.owner_name,strategy:x.response_strategy,actions:x.response_actions,dueDate:x.due_date||'',triggers:x.triggers,contingency:x.contingency_plan,fallback:x.fallback_plan,residualProbability:x.residual_probability,residualImpact:x.residual_impact,secondaryRisk:x.secondary_risk,status:x.status,linkedArtifact:x.linked_artifact,emv:x.expected_monetary_value,notes:x.notes,sortOrder:x.sort_order})),issues:(issues.data||[]).filter(x=>x.control_set_id===set.id).map(x=>({id:x.id,code:x.issue_code,title:x.title,description:x.description,owner:x.owner_name,severity:x.severity,priority:x.priority,dueDate:x.due_date||'',status:x.status,escalation:x.escalation,linkedArtifact:x.linked_artifact,resolution:x.resolution,rootCause:x.root_cause,reminderDate:x.reminder_date||'',notes:x.notes,sortOrder:x.sort_order})),stakeholders:(stakeholders.data||[]).filter(x=>x.control_set_id===set.id).map(x=>{const notes=x.stakeholder_private_notes;return{id:x.id,code:x.stakeholder_code,name:x.name,role:x.role_title,organization:x.organization,influence:x.influence,interest:x.interest,impact:x.impact,currentEngagement:x.current_engagement,desiredEngagement:x.desired_engagement,expectations:x.expectations,concerns:x.concerns,communicationPreference:x.communication_preference,owner:x.owner_name,confidentiality:x.confidentiality,status:x.status,privateNotes:(Array.isArray(notes)?notes[0]?.note:notes?.note)||'',sortOrder:x.sort_order}}),engagements:(engagements.data||[]).filter(x=>x.control_set_id===set.id).map(x=>({id:x.id,stakeholderId:x.stakeholder_id,action:x.action,owner:x.owner_name,dueDate:x.due_date||'',channel:x.channel,outcome:x.outcome,status:x.status}))});}
  for(const projectId of projectIds){const projectChanges=(changes.data||[]).filter(x=>x.project_id===projectId);if(!result.has(projectId)&&!projectChanges.length)continue;const base=result.get(projectId)||{riskPlan:{},version:0,risks:[],issues:[],stakeholders:[],engagements:[]};base.changes=projectChanges.map(x=>({id:x.id,code:x.request_code,requester:x.requester,requestedAt:x.requested_at,title:x.title,description:x.description,reason:x.reason,type:x.change_type,urgency:x.urgency,requirements:x.affected_requirements,scope:x.affected_scope,wbs:x.affected_wbs,scheduleImpact:x.schedule_impact,costImpact:Number(x.cost_impact),qualityImpact:x.quality_impact,resourceImpact:x.resource_impact,riskImpact:x.risk_impact,contractImpact:x.contract_impact,benefitsImpact:x.benefits_impact,securityImpact:x.regulatory_security_impact,assessment:x.impact_assessment,recommendation:x.recommendation,decisionComments:x.decision_comments,status:x.status,approvedAt:x.approved_at,_history:(history.data||[]).filter(h=>h.change_request_id===x.id)}));result.set(projectId,base)}return result;
}
export async function loadProjectControls(projectId){return(await loadControlsForProjects([projectId])).get(projectId)||{}}
async function loadExecutionForProjects(projectIds){
  if(!projectIds.length)return new Map();
  const [sets,reviews,reviewHistory,reports]=await Promise.all([supabase.from('execution_control_sets').select('*').in('project_id',projectIds),supabase.from('governance_reviews').select('*').in('project_id',projectIds).order('created_at'),supabase.from('governance_review_history').select('*').in('project_id',projectIds).order('created_at',{ascending:false}),supabase.from('project_status_reports').select('*').in('project_id',projectIds).order('report_date',{ascending:false})]);
  if([sets,reviews,reviewHistory,reports].some(result=>['42P01','PGRST205'].includes(result.error?.code)))return new Map(projectIds.map(id=>[id,{execution:{},reports:[]}]))
  for(const result of [sets,reviews,reviewHistory,reports])if(result.error)throw result.error;
  const setIds=(sets.data||[]).map(item=>item.id),versions=setIds.length?await supabase.from('execution_versions').select('*').in('execution_set_id',setIds).order('version',{ascending:false}):{data:[],error:null};if(versions.error)throw versions.error;
  const currentVersions=(versions.data||[]).filter(version=>(sets.data||[]).some(set=>set.id===version.execution_set_id&&set.current_version===version.version)),versionIds=currentVersions.map(item=>item.id);
  const [iterations,workItems]=await Promise.all([versionIds.length?supabase.from('delivery_iterations').select('*').in('execution_version_id',versionIds).order('sort_order'):{data:[],error:null},versionIds.length?supabase.from('delivery_work_items').select('*').in('execution_version_id',versionIds).order('sort_order'):{data:[],error:null}]);for(const result of [iterations,workItems])if(result.error)throw result.error;
  const result=new Map();for(const projectId of projectIds){const set=(sets.data||[]).find(item=>item.project_id===projectId),version=set&&currentVersions.find(item=>item.execution_set_id===set.id);result.set(projectId,{execution:{settings:version?.settings||set?.settings||{},version:set?.current_version||0,_versions:(versions.data||[]).filter(item=>item.project_id===projectId),iterations:(iterations.data||[]).filter(item=>item.project_id===projectId).map(item=>({id:item.id,code:item.iteration_code,name:item.name,type:item.iteration_type,goal:item.goal,startDate:item.start_date||'',endDate:item.end_date||'',status:item.status,capacity:Number(item.capacity),plannedPoints:Number(item.planned_points),completedPoints:Number(item.completed_points),reviewOutcome:item.review_outcome,retrospective:item.retrospective,sortOrder:item.sort_order})),workItems:(workItems.data||[]).filter(item=>item.project_id===projectId).map(item=>({id:item.id,code:item.item_code,title:item.title,type:item.item_type,iterationCode:item.iteration_code,requirement:item.requirement_ref,wbs:item.wbs_ref,owner:item.owner_name,priority:item.priority,status:item.status,estimate:Number(item.estimate),percentComplete:Number(item.percent_complete),acceptanceCriteria:item.acceptance_criteria,evidence:item.evidence,blocker:item.blocker,dueDate:item.due_date||'',completedAt:item.completed_at,sortOrder:item.sort_order})),reviews:(reviews.data||[]).filter(item=>item.project_id===projectId).map(item=>({id:item.id,code:item.review_code,type:item.review_type,title:item.title,owner:item.owner_name,scheduledDate:item.scheduled_date||'',criteria:item.criteria,evidence:item.evidence,recommendation:item.recommendation,status:item.status,decisionComments:item.decision_comments,decidedAt:item.decided_at,_history:(reviewHistory.data||[]).filter(history=>history.review_id===item.id)}))},reports:(reports.data||[]).filter(item=>item.project_id===projectId).map(item=>({...item.content,id:item.id,metrics:item.metrics,publishedAt:item.published_at,publishedBy:item.published_by}))});}return result;
}
export async function loadProjectExecution(projectId){return(await loadExecutionForProjects([projectId])).get(projectId)||{execution:{},reports:[]}}
export async function currentSession(){if(!supabase)return null;const {data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;if(!session)return null;const {data:{user},error:userError}=await supabase.auth.getUser();if(userError)return null;return{...session,user}}
export async function loadWorkspaceContext(){
  if(!backendConfigured)return{configured:false,session:null,workspace:null,role:null,projects:[]};
  const session=await currentSession();if(!session)return{configured:true,session:null,workspace:null,role:null,projects:[]};
  const {data:memberships,error:memberError}=await supabase.from('workspace_members').select('workspace_id,role,workspaces(id,name,slug)').order('joined_at',{ascending:true}).limit(1);if(memberError)throw new Error(memberError.code==='42501'?'Your account is verified, but authenticated database access has not been activated yet. Apply the latest ArkHimar database migration and retry.':memberError.message);
  const membership=memberships?.[0];if(!membership)return{configured:true,session,workspace:null,role:null,projects:[]};
  const {data:rows,error}=await supabase.from('projects').select('id,title,code,data,version,created_at,updated_at').eq('workspace_id',membership.workspace_id).is('archived_at',null).order('updated_at',{ascending:false});if(error)throw error;const projectIds=(rows||[]).map(row=>row.id),[initiation,planning,delivery,controls,execution]=await Promise.all([loadInitiationForProjects(projectIds),loadPlanningForProjects(projectIds),loadDeliveryForProjects(projectIds),loadControlsForProjects(projectIds),loadExecutionForProjects(projectIds)]);
  return{configured:true,session,workspace:membership.workspaces,role:membership.role,projects:(rows||[]).map(row=>({...row.data,...initiation.get(row.id),...execution.get(row.id),planning:{...(row.data?.planning||{}),...(planning.get(row.id)||{})},schedule:{...(row.data?.schedule||{}),...(delivery.get(row.id)?.schedule||{})},cost:{...(row.data?.cost||{}),...(delivery.get(row.id)?.cost||{})},controls:{...(row.data?.controls||{}),...(controls.get(row.id)||{})},id:row.id,title:row.title,code:row.code,_version:row.version}))};
}
export async function bootstrapWorkspace(name){const {data,error}=await supabase.rpc('bootstrap_workspace',{workspace_name:name});if(error)throw error;return data}
export async function createProject(workspaceId,project,userId){const payload=publicProject(project);const {data,error}=await supabase.from('projects').insert({id:project.id,workspace_id:workspaceId,title:project.title,code:project.code,data:payload,created_by:userId}).select('id,title,code,data,version').single();if(error)throw error;return{...data.data,id:data.id,title:data.title,code:data.code,_version:data.version}}
export async function updateProject(project){const payload=publicProject(project);const {data,error}=await supabase.from('projects').update({title:project.title,code:project.code,data:payload}).eq('id',project.id).eq('version',project._version||1).select('version').maybeSingle();if(error)throw error;if(!data)throw new Error('This project changed in another session. Reload before saving again.');project._version=data.version;return project}
export async function saveBusinessCase(projectId,business){const {options=[],status,version=1,_decisions,...content}=business,{data,error}=await supabase.rpc('save_business_case',{target_project:projectId,expected_version:version,case_content:content,case_options:options});if(error)throw error;return data}
export async function transitionBusinessCase(projectId,version,status,comments=''){const {data,error}=await supabase.rpc('transition_business_case',{target_project:projectId,expected_version:version,next_status:status,decision_comments:comments});if(error)throw error;return data}
export async function saveProjectCharter(projectId,charter){const {status,version=1,approvedSnapshot,_decisions,...content}=charter,{data,error}=await supabase.rpc('save_project_charter',{target_project:projectId,expected_version:version,charter_content:content});if(error)throw error;return data}
export async function transitionProjectCharter(projectId,version,status,comments=''){const {data,error}=await supabase.rpc('transition_project_charter',{target_project:projectId,expected_version:version,next_status:status,decision_comments:comments});if(error)throw error;return data}
export async function saveCorePlanning(projectId,planning){const {requirements=[],wbs=[],subsidiaryPlans=[],version=1,status,baseline,_baselines,...content}=planning;const masterKeys=['planSummary','governanceApproach','lifecycleModel','thresholds','escalationRules','tailoringDecisions'];const master=Object.fromEntries(masterKeys.map(key=>[key,content[key]||''])),scope=Object.fromEntries(Object.entries(content).filter(([key])=>!masterKeys.includes(key)));const {data,error}=await supabase.rpc('save_core_planning',{target_project:projectId,expected_version:version,master_content:master,scope_content:scope,plan_items:subsidiaryPlans,requirement_items:requirements,wbs_items:wbs});if(error)throw error;return data}
export async function approveScopeBaseline(projectId,version,name='Scope baseline'){const {data,error}=await supabase.rpc('approve_scope_baseline',{target_project:projectId,expected_version:version,baseline_name:name});if(error)throw error;return data}
export async function beginScopeRevision(projectId,version,changeReference){const {data,error}=await supabase.rpc('begin_scope_revision',{target_project:projectId,expected_version:version,change_reference:changeReference});if(error)throw error;return data}
export async function saveScheduleControl(projectId,schedule){const {tasks=[],dependencies=[],calendar={},version=1,status,baseline,_baselines,...settings}=schedule,{data,error}=await supabase.rpc('save_schedule_control',{target_project:projectId,expected_version:version,calendar_content:calendar,setting_content:settings,task_items:tasks,dependency_items:dependencies});if(error)throw error;return data}
export async function saveCostControl(projectId,cost){const {items=[],cashFlow=[],version=1,status,baseline,_baselines,...settings}=cost,{data,error}=await supabase.rpc('save_cost_control',{target_project:projectId,expected_version:version,setting_content:settings,cost_items_payload:items,cash_flow_payload:cashFlow});if(error)throw error;return data}
export async function approveDeliveryBaseline(projectId,type,version,name){const {data,error}=await supabase.rpc('approve_delivery_baseline',{target_project:projectId,baseline_type:type,expected_version:version,baseline_name:name});if(error)throw error;return data}
export async function beginDeliveryRevision(projectId,type,version,reference){const {data,error}=await supabase.rpc('begin_delivery_revision',{target_project:projectId,baseline_type:type,expected_version:version,change_reference:reference});if(error)throw error;return data}
export async function saveProjectControls(projectId,controls){const {riskPlan={},risks=[],issues=[],stakeholders=[],engagements=[],changes=[],version=0}=controls,{data,error}=await supabase.rpc('save_project_controls',{target_project:projectId,expected_version:version,plan_content:riskPlan,risks_payload:risks,issues_payload:issues,stakeholders_payload:stakeholders,engagements_payload:engagements,changes_payload:changes});if(error)throw error;return data}
export async function transitionChangeRequest(changeId,status,comments=''){const {data,error}=await supabase.rpc('transition_change_request',{target_change:changeId,next_status:status,transition_comments:comments});if(error)throw error;return data}
export async function saveExecutionControl(projectId,execution){const {settings={},iterations=[],workItems=[],reviews=[],version=0}=execution,{data,error}=await supabase.rpc('save_execution_control',{target_project:projectId,expected_version:version,setting_content:settings,iteration_items:iterations,work_items:workItems,review_items:reviews});if(error)throw error;return data}
export async function transitionGovernanceReview(reviewId,status,comments=''){const {data,error}=await supabase.rpc('transition_governance_review',{target_review:reviewId,next_status:status,transition_comments:comments});if(error)throw error;return data}
export async function publishStatusReport(projectId,report,metrics){const {data,error}=await supabase.rpc('publish_status_report',{target_project:projectId,report_payload:report,metric_snapshot:metrics});if(error)throw error;return data}
export async function downloadProjectPack(projectId,format){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/projects/export',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({projectId,format})});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.message||result.error||'Project export failed')}const blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',filename=disposition.match(/filename="([^"]+)"/)?.[1]||`ARKHIMAR_PM_project.${format}`;return{blob,filename}}
export async function listDocuments(projectId){const {data,error}=await supabase.from('project_documents').select('id,filename,content_type,size_bytes,created_at,storage_path').eq('project_id',projectId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function listControlledDocuments(projectId){
  const {data:documents,error}=await supabase.from('controlled_documents').select('*').eq('project_id',projectId).order('updated_at',{ascending:false});if(error)throw error;
  const ids=(documents||[]).map(document=>document.id);if(!ids.length)return[];
  const [{data:versions,error:versionError},{data:shares,error:shareError}]=await Promise.all([supabase.from('controlled_document_versions').select('*').in('document_id',ids).order('version',{ascending:false}),canReadDocumentShares()?supabase.from('controlled_document_shares').select('id,document_id,version,format,expires_at,max_downloads,download_count,revoked_at,created_at').in('document_id',ids).order('created_at',{ascending:false}):Promise.resolve({data:[],error:null})]);if(versionError)throw versionError;if(shareError)throw shareError;
  return documents.map(document=>({...document,versions:(versions||[]).filter(version=>version.document_id===document.id),shares:(shares||[]).filter(share=>share.document_id===document.id)}));
}
function canReadDocumentShares(){return Boolean(supabase)}
export async function createControlledDocument(projectId,values){const {data,error}=await supabase.rpc('create_controlled_document',{target_project:projectId,document_id_code:values.document_code,document_type:values.artifact_type,document_title:values.title,document_owner:values.owner_name||'',document_confidentiality:values.confidentiality||'Internal',document_tags:(values.tags||'').split(',').map(tag=>tag.trim()).filter(Boolean),document_content:{summary:values.summary||''},revision_note:values.revision_notes||''});if(error)throw error;return data}
export async function transitionControlledDocument(documentId,status){const {error}=await supabase.rpc('transition_controlled_document',{target_document:documentId,next_status:status});if(error)throw error}
export async function reviseControlledDocument(documentId,summary,revisionNotes){const {data,error}=await supabase.rpc('revise_controlled_document',{target_document:documentId,document_content:{summary},revision_note:revisionNotes});if(error)throw error;return data}
async function documentRequest(path,payload,method='POST'){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch(path,{method,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.message||result.error||'Document request failed')}return response}
export async function downloadControlledDocument(documentId,version,format){const response=await documentRequest('/api/v1/documents/export',{documentId,version,format}),blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',filename=disposition.match(/filename="([^"]+)"/)?.[1]||`ArkHimar-document.${format}`;return{blob,filename}}
export async function createDocumentShare(documentId,version,format,expiresInHours=168,maxDownloads=10){const response=await documentRequest('/api/v1/documents/shares',{documentId,version,format,expiresInHours,maxDownloads});return response.json()}
export async function revokeDocumentShare(documentId,shareId){const response=await documentRequest('/api/v1/documents/shares',{documentId,shareId},'DELETE');return response.json()}
export async function importResourceDraft(projectId,resource){const {data,error}=await supabase.rpc('import_resource_draft',{target_project:projectId,source_slug:resource.slug,source_version:resource.version});if(error)throw error;return data}
export async function uploadDocument({workspaceId,projectId,userId,file}){const safe=file.name.normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-120),path=`${workspaceId}/${projectId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from('project-documents').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await supabase.from('project_documents').insert({workspace_id:workspaceId,project_id:projectId,storage_path:path,filename:file.name,content_type:file.type,size_bytes:file.size,uploaded_by:userId}).select().single();if(error){await supabase.storage.from('project-documents').remove([path]);throw error}return data}
export async function signedDocumentUrl(path){const {data,error}=await supabase.storage.from('project-documents').createSignedUrl(path,60);if(error)throw error;return data.signedUrl}
export async function loadWorkspaceTools(workspaceId,role){
  const canAdmin=['owner','admin'].includes(role),canManage=canAdmin||role==='project_manager';
  const requests=[
    supabase.from('workspace_brand_settings').select('*').eq('workspace_id',workspaceId).maybeSingle(),
    supabase.from('message_templates').select('*').eq('workspace_id',workspaceId).is('archived_at',null).order('updated_at',{ascending:false}),
    canManage?supabase.from('outbound_messages').select('id,subject,recipients,status,provider_message_id,error_message,created_at,sent_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(25):Promise.resolve({data:[],error:null}),
    canManage?supabase.from('form_submissions').select('id,form_id,submitter_name,submitter_email,message,fields,received_at').eq('workspace_id',workspaceId).order('received_at',{ascending:false}).limit(25):Promise.resolve({data:[],error:null}),
    supabase.from('project_documents').select('id,project_id,filename,size_bytes').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(100)
  ];
  const [brand,templates,messages,submissions,documents]=await Promise.all(requests);
  for(const result of [brand,templates,messages,submissions,documents])if(result.error)throw result.error;
  let apiKeys=[];
  if(canAdmin){const {data,error}=await supabase.rpc('list_workspace_api_keys',{target_workspace:workspaceId});if(error)throw error;apiKeys=data||[]}
  if(brand.data){for(const [pathField,urlField] of [['logo_path','logo_url'],['letterhead_path','letterhead_url']])if(brand.data[pathField]){const {data}=await supabase.storage.from('workspace-brand-assets').createSignedUrl(brand.data[pathField],300);brand.data[urlField]=data?.signedUrl||''}}
  return{brand:brand.data,templates:templates.data||[],messages:messages.data||[],submissions:submissions.data||[],documents:documents.data||[],apiKeys,revealedKey:null};
}
export async function saveWorkspaceBrand(workspaceId,userId,values){const row={workspace_id:workspaceId,sender_name:values.sender_name,reply_to:values.reply_to||null,primary_color:values.primary_color,accent_color:values.accent_color,background_color:values.background_color,footer_text:values.footer_text,updated_by:userId,updated_at:new Date().toISOString()};const {data,error}=await supabase.from('workspace_brand_settings').upsert(row).select().single();if(error)throw error;return data}
export async function uploadBrandAsset({workspaceId,userId,file,kind}){const safe=file.name.normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-100),path=`${workspaceId}/${kind}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('workspace-brand-assets').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const field=kind==='logo'?'logo_path':'letterhead_path',{data:current}=await supabase.from('workspace_brand_settings').select('*').eq('workspace_id',workspaceId).maybeSingle(),values={workspace_id:workspaceId,sender_name:current?.sender_name||'ArkHimar PM',reply_to:current?.reply_to||null,primary_color:current?.primary_color||'#191916',accent_color:current?.accent_color||'#B86B42',background_color:current?.background_color||'#F5F3ED',footer_text:current?.footer_text||'Generated with ArkHimar PM',logo_path:current?.logo_path||null,letterhead_path:current?.letterhead_path||null,updated_by:userId,updated_at:new Date().toISOString(),[field]:path};const {data,error:updateError}=await supabase.from('workspace_brand_settings').upsert(values).select().single();if(updateError){await supabase.storage.from('workspace-brand-assets').remove([path]);throw updateError}return data}
export async function saveMessageTemplate(workspaceId,userId,template){const values={workspace_id:workspaceId,name:template.name,kind:template.kind,subject:template.subject,blocks:template.blocks,created_by:userId};const query=template.id?supabase.from('message_templates').update({...values,version:(template.version||1)+1,updated_at:new Date().toISOString()}).eq('id',template.id):supabase.from('message_templates').insert(values);const {data,error}=await query.select().single();if(error)throw error;return data}
export async function createWorkspaceApiKey(workspaceId,label,scopes=['forms:submit']){const {data,error}=await supabase.rpc('create_workspace_api_key',{target_workspace:workspaceId,key_label:label,key_scopes:scopes});if(error)throw error;return data?.[0]}
export async function revokeWorkspaceApiKey(id){const {error}=await supabase.rpc('revoke_workspace_api_key',{target_key:id});if(error)throw error}
export async function sendWorkspaceMessage(payload){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/messages/send',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Message delivery failed');return result}
export async function loadWorkspaceTeam(workspaceId,role){const {data:members,error}=await supabase.from('workspace_members').select('user_id,role,joined_at').eq('workspace_id',workspaceId).order('joined_at');if(error)throw error;const ids=(members||[]).map(member=>member.user_id);let profiles=[];if(ids.length){const result=await supabase.from('profiles').select('id,display_name').in('id',ids);if(result.error)throw result.error;profiles=result.data||[]}const names=new Map(profiles.map(profile=>[profile.id,profile.display_name]));let invitations=[];if(['owner','admin'].includes(role)){const result=await supabase.from('workspace_invitations').select('id,email,role,delivery_status,expires_at,accepted_at,revoked_at,created_at').eq('workspace_id',workspaceId).is('accepted_at',null).is('revoked_at',null).order('created_at',{ascending:false});if(result.error)throw result.error;invitations=result.data||[]}return{members:(members||[]).map(member=>({...member,display_name:names.get(member.user_id)||''})),invitations}}
export async function inviteWorkspaceMember(payload){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/workspace/invitations',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Invitation could not be sent');return result}
export async function revokeWorkspaceInvitation(workspaceId,invitationId){const session=await currentSession();if(!session)throw new Error('Your session has expired. Sign in again.');const response=await fetch('/api/v1/workspace/invitations',{method:'DELETE',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({workspaceId,invitationId})}),result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Invitation could not be revoked');return result}
export async function updateWorkspaceMemberRole(workspaceId,userId,role){const {data,error}=await supabase.from('workspace_members').update({role}).eq('workspace_id',workspaceId).eq('user_id',userId).select('user_id,role').maybeSingle();if(error)throw error;if(!data)throw new Error('Your role does not permit this membership change.');return data}
export async function removeWorkspaceMember(workspaceId,userId){const {data,error}=await supabase.from('workspace_members').delete().eq('workspace_id',workspaceId).eq('user_id',userId).select('user_id').maybeSingle();if(error)throw error;if(!data)throw new Error('Your role does not permit removing this member.');return data}
export async function mfaRequirement(){const [{data:factors,error:factorError},{data:assurance,error:assuranceError}]=await Promise.all([supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);if(factorError)throw factorError;if(assuranceError)throw assuranceError;const factor=factors.totp?.[0]||null;return{factor,currentLevel:assurance.currentLevel,nextLevel:assurance.nextLevel,required:Boolean(factor&&assurance.currentLevel==='aal1'&&assurance.nextLevel==='aal2')}}
export async function verifyMfaCode(factorId,code){const {data,error}=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(error)throw error;return data}
export async function signOut(){if(supabase)await supabase.auth.signOut({scope:'local'});location.replace('/pm/login/')}
