const STORAGE_KEY='arkhimar.pm.projects.v1';
const readProjects=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};
const writeProjects=projects=>localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));
const list=document.querySelector('[data-project-list]');
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function render(){const projects=readProjects();document.querySelector('[data-count]').textContent=projects.length;const readiness=Math.min(100,projects.length?34+projects.filter(p=>p.problem&&p.outcome).length*8:0);document.querySelector('[data-readiness]').textContent=`${readiness}%`;document.querySelector('.readiness-ring').style.setProperty('--progress',`${readiness}%`);document.querySelector('[data-next-copy]').textContent=projects.length?'Complete sponsorship, charter, scope, schedule, budget, risk and governance controls to improve readiness.':'Create your first project. ArkHimar PM will turn its delivery setup into a transparent readiness checklist.';if(!projects.length){list.innerHTML='<div class="empty-state"><strong>No projects yet</strong><p>Create a project to begin building its business case, charter and readiness checklist.</p></div>';return}list.innerHTML=projects.map(p=>`<article class="project-row"><div class="project-mark">${escapeHtml(p.code).slice(0,3)}</div><div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.code)} · ${escapeHtml(p.approach)} · ${escapeHtml(p.industry)}</p></div><span class="badge">Setup</span><small>${escapeHtml(p.priority)} priority</small></article>`).join('')}
const projectDialog=document.querySelector('[data-project-dialog]');const projectForm=document.querySelector('[data-project-form]');const steps=[...document.querySelectorAll('[data-step]')];let step=1;
function showStep(next){step=next;steps.forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===step));document.querySelector('[data-step-label]').textContent=`${step} OF ${steps.length}`;document.querySelector('[data-track]').style.width=`${step/steps.length*100}%`;document.querySelector('[data-back]').disabled=step===1;document.querySelector('[data-next]').innerHTML=step===steps.length?'Create project <span>＋</span>':'Continue →';document.querySelector('[data-wizard-status]').textContent=''}
function openProject(){document.querySelector('[data-command-dialog]')?.close();projectDialog.showModal();showStep(1);setTimeout(()=>projectForm.elements.title.focus(),50)}
document.querySelectorAll('[data-new-project]').forEach(button=>button.addEventListener('click',openProject));document.querySelector('[data-back]').addEventListener('click',()=>showStep(Math.max(1,step-1)));document.querySelector('[data-next]').addEventListener('click',()=>{const current=steps[step-1];const fields=[...current.querySelectorAll('input,select,textarea')];const invalid=fields.find(field=>!field.checkValidity());if(invalid){invalid.reportValidity();document.querySelector('[data-wizard-status]').textContent='Complete the required fields.';return}if(step<steps.length){showStep(step+1);return}const data=Object.fromEntries(new FormData(projectForm));const projects=readProjects();projects.unshift({...data,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'setup'});writeProjects(projects);projectForm.reset();projectDialog.close();render()});
const rail=document.querySelector('#rail');document.querySelector('[data-collapse]').addEventListener('click',()=>rail.classList.toggle('collapsed'));document.querySelector('[data-mobile]').addEventListener('click',event=>{const open=rail.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open))});
const commandDialog=document.querySelector('[data-command-dialog]');const openCommand=()=>commandDialog.showModal();document.querySelector('[data-command]').addEventListener('click',openCommand);addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openCommand()}if(event.key==='Escape')rail.classList.remove('open')});
render();
