import {renderEmailHtml} from '../lib/email-template.mjs';
import {createWorkspaceApiKey,loadWorkspaceTools,revokeWorkspaceApiKey,saveMessageTemplate,saveWorkspaceBrand,sendWorkspaceMessage,uploadBrandAsset} from './backend.js';

let cache=null;
const esc=(value='')=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const emailList=value=>String(value||'').split(',').map(item=>item.trim()).filter(Boolean);
const defaultBrand={sender_name:'ArkHimar PM',reply_to:'projects@arkhimar.com',primary_color:'#191916',accent_color:'#B86B42',background_color:'#F5F3ED',footer_text:'Generated with ArkHimar PM'};

export async function loadStudio(context,force=false){if(!cache||force)cache=await loadWorkspaceTools(context.workspace.id,context.role);return cache}

function blocksFromForm(form){const values=Object.fromEntries(new FormData(form));return[
  {type:'heading',text:values.heading},
  {type:'text',text:values.message},
  ...(values.button_label&&values.button_url?[{type:'button',label:values.button_label,url:values.button_url}]:[]),
  {type:'divider'},
  {type:'signature',text:values.signature}
]}
function composerPayload(form,context){const values=Object.fromEntries(new FormData(form));return{workspaceId:context.workspace.id,projectId:values.project_id||null,templateId:values.template_id||null,to:emailList(values.to),cc:emailList(values.cc),bcc:[],subject:values.subject,preheader:values.preheader,blocks:blocksFromForm(form),attachmentIds:[...form.querySelectorAll('[name=attachment_ids]:checked')].map(input=>input.value),idempotencyKey:crypto.randomUUID()}}
function projectOptions(projects){return`<option value="">Workspace message</option>${projects.map(project=>`<option value="${project.id}">${esc(project.code)} · ${esc(project.title)}</option>`).join('')}`}

export function renderCommunications(context,projects){
  if(!cache)return'<section class="panel"><p>Loading Communications Studio…</p></section>';
  const brand={...defaultBrand,...cache.brand},canManage=['owner','admin','project_manager'].includes(context.role),canBrand=['owner','admin'].includes(context.role);
  return`<header class="page-heading"><div><p>COMMUNICATIONS STUDIO</p><h1>Write beautifully. Send responsibly.</h1><span>Branded email and letter templates with server-authorized delivery.</span></div></header>
  <div class="studio-grid"><section class="panel composer-panel"><div class="section-title"><div><p class="eyebrow">COMPOSER</p><h2>Email &amp; letter editor</h2></div><span class="status-chip">Structured content</span></div>
  ${canManage?`<form data-message-composer class="data-form"><input type="hidden" name="template_id"><div class="form-grid compact"><label>Format<select name="kind"><option value="email">Email</option><option value="letter">Letter</option></select></label><label>Project<select name="project_id">${projectOptions(projects)}</select></label><label class="wide">Template name<input name="template_name" required value="Client update"></label><label class="wide">Recipients<input name="to" type="text" placeholder="client@example.com, sponsor@example.com"></label><label class="wide">CC<input name="cc" type="text" placeholder="Optional comma-separated addresses"></label><label class="wide">Subject<input name="subject" required value="Project update from ArkHimar PM"></label><label class="wide">Preview text<input name="preheader" maxlength="180" value="A clear project update prepared for you."></label><label class="wide">Bold header<input name="heading" required value="A thoughtful update for your project"></label><label class="wide">Friendly message<textarea name="message" rows="7" required>We are pleased to share this update with you. The project team remains focused on the agreed priorities and will keep you informed as decisions progress.</textarea></label><label>Button text<input name="button_label" value="Review project"></label><label>Button URL<input name="button_url" type="url" value="https://www.arkhimar.com"></label><label class="wide">Signature<textarea name="signature" rows="3">Warm regards,\nThe ArkHimar team</textarea></label></div>
  ${cache.documents.length?`<fieldset class="attachment-picker"><legend>Attach private project documents (optional)</legend>${cache.documents.map(doc=>`<label><input type="checkbox" name="attachment_ids" value="${doc.id}"> ${esc(doc.filename)} <small>${(Number(doc.size_bytes)/1048576).toFixed(2)} MB</small></label>`).join('')}</fieldset>`:''}
  <footer><div class="button-group"><button class="secondary" type="button" data-save-template>Save template</button><button class="secondary" type="button" data-download-letter>Download letter</button><button class="secondary" type="button" data-print-letter>Print / PDF</button><button class="primary" type="submit">Send email securely</button></div></footer></form>`:'<p class="permission-note">Your role can view templates and history but cannot send or edit communications.</p>'}</section>
  <aside class="panel preview-panel"><p class="eyebrow">LIVE PREVIEW</p><iframe title="Branded message preview" sandbox="allow-popups" data-message-preview></iframe></aside></div>
  <div class="dual-grid studio-lower"><section class="panel"><div class="section-title"><div><p class="eyebrow">WORKSPACE BRAND</p><h2>Identity &amp; letterhead</h2></div></div>${canBrand?`<form data-brand-form class="data-form"><div class="form-grid compact"><label>Sender name<input name="sender_name" required value="${esc(brand.sender_name)}"></label><label>Reply-to email<input name="reply_to" type="email" value="${esc(brand.reply_to||'')}"></label><label>Primary color<input name="primary_color" type="color" value="${esc(brand.primary_color)}"></label><label>Accent color<input name="accent_color" type="color" value="${esc(brand.accent_color)}"></label><label>Background color<input name="background_color" type="color" value="${esc(brand.background_color)}"></label><label>Footer text<input name="footer_text" maxlength="500" value="${esc(brand.footer_text)}"></label></div><footer><button class="primary" type="submit">Save brand</button></footer></form><form class="brand-upload" data-brand-upload><label>Logo<input type="file" name="logo" accept=".png,.jpg,.jpeg,.webp"></label><label>Letterhead<input type="file" name="letterhead" accept=".png,.jpg,.jpeg,.webp,.pdf"></label><button class="secondary" type="submit">Upload selected asset</button><p>Private workspace assets · maximum 5 MB.</p></form>`:'<p class="helper">Brand settings are managed by workspace owners and admins.</p>'}</section>
  <section class="panel"><div class="section-title"><div><p class="eyebrow">TEMPLATE LIBRARY</p><h2>Reusable messages</h2></div><span>${cache.templates.length}</span></div>${cache.templates.length?`<div class="record-list">${cache.templates.map(template=>`<article><div><strong>${esc(template.name)}</strong><p>${esc(template.kind)} · v${template.version} · ${esc(template.subject)}</p></div>${canManage?`<button class="secondary" type="button" data-load-template="${template.id}">Use</button>`:''}</article>`).join('')}</div>`:'<p class="helper">Save your first email or letter template from the composer.</p>'}<h3 class="subheading">Delivery history</h3>${cache.messages.length?`<div class="record-list">${cache.messages.map(message=>`<article><div><strong>${esc(message.subject)}</strong><p>${esc(message.status)} · ${new Date(message.created_at).toLocaleString()}</p></div><span class="status-chip ${message.status==='sent'?'approved':''}">${esc(message.status)}</span></article>`).join('')}</div>`:'<p class="helper">Sent and failed messages will appear here.</p>'}</section></div>`
}

export function renderIntegrations(context){
  if(!cache)return'<section class="panel"><p>Loading Integration Hub…</p></section>';
  const isAdmin=['owner','admin'].includes(context.role),endpoint=`${location.origin}/api/v1/forms/submit`;
  return`<header class="page-heading"><div><p>INTEGRATION HUB</p><h1>Connect forms to ArkHimar PM.</h1><span>Use a scoped API key from Postman, n8n, Zapier, Make or your own server.</span></div></header><div class="content-grid"><section class="panel"><div class="section-title"><div><p class="eyebrow">FORM SUBMISSION API</p><h2>Endpoint and credentials</h2></div><span class="status-chip">60 requests/minute</span></div><label class="endpoint-field">POST endpoint<input readonly value="${esc(endpoint)}"></label>${isAdmin?`<form class="inline-form api-key-form" data-create-api-key><input name="label" required minlength="2" maxlength="100" placeholder="e.g. TS Academy assignment"><button type="submit">Create scoped key</button></form>`:'<p class="permission-note">Only workspace owners and admins can create or revoke API keys.</p>'}${cache.revealedKey?`<div class="revealed-key"><strong>Copy this key now. It will not be shown again.</strong><code>${esc(cache.revealedKey)}</code><button class="secondary" type="button" data-copy-key>Copy API key</button></div>`:''}<pre class="code-sample">curl -X POST '${esc(endpoint)}' \\
  -H 'x-api-key: YOUR_ARKHIMAR_KEY' \\
  -H 'content-type: application/json' \\
  -d '{"formId":"ts-academy-assignment","name":"Ada","email":"ada@example.com","message":"My connected form works","fields":{"course":"AI and Automation"}}'</pre><p class="helper">Keep secret keys in your automation platform’s credential store. Never embed them in public browser JavaScript.</p></section><aside class="panel"><p class="eyebrow">WHAT HAPPENS</p><h2>Submission flow</h2><ol class="flow-list"><li>ArkHimar validates the scoped key.</li><li>The server enforces rate limits and tenant identity.</li><li>The payload is validated and stored.</li><li>An optional branded notification is sent through Resend.</li><li>The request is added to the audit-ready submission inbox.</li></ol></aside></div>
  <div class="dual-grid studio-lower"><section class="panel"><div class="section-title"><div><p class="eyebrow">API KEYS</p><h2>Active credentials</h2></div><span>${cache.apiKeys.filter(key=>!key.revoked_at).length} active</span></div>${cache.apiKeys.length?`<div class="record-list">${cache.apiKeys.map(key=>`<article><div><strong>${esc(key.label)}</strong><p>${esc(key.key_prefix)}… · ${key.scopes.map(esc).join(', ')} · ${key.usage_count} requests</p></div>${!key.revoked_at?`<button class="row-action" type="button" data-revoke-key="${key.id}">Revoke</button>`:'<span class="status-chip">Revoked</span>'}</article>`).join('')}</div>`:'<p class="helper">No keys created yet.</p>'}</section><section class="panel"><div class="section-title"><div><p class="eyebrow">SUBMISSION INBOX</p><h2>Connected form responses</h2></div><span>${cache.submissions.length}</span></div>${cache.submissions.length?`<div class="record-list">${cache.submissions.map(item=>`<article><div><strong>${esc(item.submitter_name||item.submitter_email||'Anonymous response')}</strong><p>${esc(item.form_id)} · ${new Date(item.received_at).toLocaleString()}<br>${esc(item.message||'No message')}</p></div></article>`).join('')}</div>`:'<p class="helper">Validated API submissions will appear here.</p>'}</section></div>`
}

export function bindStudio(context,{notify,refresh}){
  const composer=document.querySelector('[data-message-composer]'),preview=document.querySelector('[data-message-preview]');
  const updatePreview=()=>{if(!composer||!preview)return;const values=Object.fromEntries(new FormData(composer)),brandForm=document.querySelector('[data-brand-form]'),brand={...defaultBrand,...cache.brand,...(brandForm?Object.fromEntries(new FormData(brandForm)): {})};preview.srcdoc=renderEmailHtml({subject:values.subject,preheader:values.preheader,blocks:blocksFromForm(composer),brand})};
  composer?.addEventListener('input',updatePreview);updatePreview();
  composer?.addEventListener('submit',async event=>{event.preventDefault();const button=composer.querySelector('[type=submit]'),payload=composerPayload(composer,context);if(!payload.to.length){notify('Recipient required','Add at least one valid email address.');return}button.disabled=true;button.textContent='Sending…';try{await sendWorkspaceMessage(payload);notify('Email sent','The branded message was accepted by the delivery provider.');await refresh()}catch(error){notify('Email not sent',error.message)}finally{button.disabled=false;button.textContent='Send email securely'}});
  document.querySelector('[data-save-template]')?.addEventListener('click',async()=>{const values=Object.fromEntries(new FormData(composer));try{await saveMessageTemplate(context.workspace.id,context.session.user.id,{id:values.template_id||null,name:values.template_name,kind:values.kind,subject:values.subject,blocks:blocksFromForm(composer)});notify('Template saved','The reusable workspace template is ready.');await refresh()}catch(error){notify('Template not saved',error.message)}});
  document.querySelector('[data-download-letter]')?.addEventListener('click',()=>{const values=Object.fromEntries(new FormData(composer)),blob=new Blob([renderEmailHtml({subject:values.subject,blocks:blocksFromForm(composer),brand:{...defaultBrand,...cache.brand}})],{type:'text/html'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${String(values.template_name||'letter').replace(/[^a-z0-9_-]+/gi,'-')}.html`;link.click();URL.revokeObjectURL(link.href)});
  document.querySelector('[data-print-letter]')?.addEventListener('click',()=>preview?.contentWindow?.print());
  document.querySelectorAll('[data-load-template]').forEach(button=>button.addEventListener('click',()=>{const template=cache.templates.find(item=>item.id===button.dataset.loadTemplate);if(!template||!composer)return;composer.elements.template_id.value=template.id;composer.elements.template_name.value=template.name;composer.elements.kind.value=template.kind;composer.elements.subject.value=template.subject;for(const block of template.blocks){if(block.type==='heading')composer.elements.heading.value=block.text;if(block.type==='text')composer.elements.message.value=block.text;if(block.type==='button'){composer.elements.button_label.value=block.label;composer.elements.button_url.value=block.url}if(block.type==='signature')composer.elements.signature.value=block.text}updatePreview();composer.scrollIntoView({behavior:'smooth'})}));
  document.querySelector('[data-brand-form]')?.addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button'),values=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;try{cache.brand=await saveWorkspaceBrand(context.workspace.id,context.session.user.id,values);notify('Brand saved','New messages and letters now use this workspace identity.');await refresh()}catch(error){notify('Brand not saved',error.message)}finally{button.disabled=false}});
  document.querySelector('[data-brand-form]')?.addEventListener('input',updatePreview);
  document.querySelector('[data-brand-upload]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,logo=form.elements.logo.files[0],letterhead=form.elements.letterhead.files[0],file=logo||letterhead,kind=logo?'logo':'letterhead';if(!file){notify('Choose an asset','Select a logo or letterhead file first.');return}if(file.size>5242880){notify('Asset too large','Brand assets must be no larger than 5 MB.');return}try{cache.brand=await uploadBrandAsset({workspaceId:context.workspace.id,userId:context.session.user.id,file,kind});notify('Brand asset uploaded',`${file.name} is stored privately.`);await refresh()}catch(error){notify('Upload failed',error.message)}});
  document.querySelector('[data-create-api-key]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const key=await createWorkspaceApiKey(context.workspace.id,new FormData(form).get('label'));cache=await loadWorkspaceTools(context.workspace.id,context.role);cache.revealedKey=key.api_key;await refresh(false)}catch(error){notify('Key not created',error.message)}finally{button.disabled=false}});
  document.querySelector('[data-copy-key]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(cache.revealedKey);notify('API key copied','Store it in your automation tool’s secret or credential manager.')} );
  document.querySelectorAll('[data-revoke-key]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Revoke this API key? Existing integrations using it will stop immediately.'))return;try{await revokeWorkspaceApiKey(button.dataset.revokeKey);notify('API key revoked','Requests using that credential will now be rejected.');await refresh()}catch(error){notify('Key not revoked',error.message)}}));
}
