import {inviteWorkspaceMember,loadWorkspaceTeam,removeWorkspaceMember,revokeWorkspaceInvitation,updateWorkspaceMemberRole} from './backend.js';

let cache=null;
const esc=(value='')=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const roleName=role=>String(role||'').replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());

export async function loadTeam(context,force=false){if(!cache||force)cache=await loadWorkspaceTeam(context.workspace.id,context.role);return cache}

export function renderTeam(context){
  if(!cache)return'<section class="panel"><p>Loading workspace team…</p></section>';
  const canAdmin=['owner','admin'].includes(context.role),isOwner=context.role==='owner',now=Date.now();
  return`<header class="page-heading"><div><p>TEAM &amp; ACCESS</p><h1>Invite people. Control access.</h1><span>Workspace roles are enforced by the server and PostgreSQL row-level security.</span></div></header>
  <div class="content-grid"><section class="panel"><div class="section-title"><div><p class="eyebrow">WORKSPACE MEMBERS</p><h2>${cache.members.length} active member${cache.members.length===1?'':'s'}</h2></div></div><div class="record-list team-list">${cache.members.map(member=>{const self=member.user_id===context.session.user.id,protectedRow=member.role==='owner'||(!isOwner&&member.role==='admin')||self;const choices=(isOwner?['admin','project_manager','member','viewer']:['project_manager','member','viewer']).map(role=>`<option value="${role}" ${member.role===role?'selected':''}>${roleName(role)}</option>`).join('');return`<article><div><strong>${esc(member.display_name||(self?'You':'Workspace member'))}</strong><p>${roleName(member.role)} · joined ${new Date(member.joined_at).toLocaleDateString()}</p></div>${canAdmin&&!protectedRow?`<div class="member-actions"><select data-member-role="${member.user_id}" aria-label="Role for ${esc(member.display_name||'workspace member')}">${choices}</select><button class="row-action" type="button" data-remove-member="${member.user_id}">Remove</button></div>`:`<span class="status-chip ${member.role==='owner'?'approved':''}">${self?'Your account':roleName(member.role)}</span>`}</article>`}).join('')}</div></section>
  <aside class="panel"><p class="eyebrow">ROLE BOUNDARIES</p><h2>Least access by default</h2><ul class="flow-list"><li><strong>Owner</strong> controls admins and every workspace setting.</li><li><strong>Admin</strong> manages members, projects and integrations.</li><li><strong>Project manager</strong> creates and updates projects and communications.</li><li><strong>Member</strong> contributes private documents.</li><li><strong>Viewer</strong> has read-only access.</li></ul></aside></div>
  ${canAdmin?`<div class="dual-grid studio-lower"><section class="panel"><div class="section-title"><div><p class="eyebrow">INVITE A TEAM MEMBER</p><h2>Send a secure invitation</h2></div><span class="status-chip">Expires automatically</span></div><form class="data-form" data-invite-member><div class="form-grid compact"><label class="wide">Email address<input name="email" type="email" required autocomplete="email" placeholder="colleague@example.com"></label><label>Workspace role<select name="role">${(isOwner?['admin','project_manager','member','viewer']:['project_manager','member','viewer']).map(role=>`<option value="${role}">${roleName(role)}</option>`).join('')}</select></label><label>Expires after<select name="expires"><option value="7">7 days</option><option value="3">3 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label></div><footer><p>The recipient must sign in with the invited email address.</p><button class="primary" type="submit">Send invitation</button></footer></form></section><section class="panel"><div class="section-title"><div><p class="eyebrow">PENDING INVITATIONS</p><h2>${cache.invitations.length} awaiting response</h2></div></div>${cache.invitations.length?`<div class="record-list">${cache.invitations.map(invite=>`<article><div><strong>${esc(invite.email)}</strong><p>${roleName(invite.role)} · ${invite.delivery_status} · ${new Date(invite.expires_at).getTime()<now?'expired':`expires ${new Date(invite.expires_at).toLocaleDateString()}`}</p></div><button class="row-action" type="button" data-revoke-invite="${invite.id}">Revoke</button></article>`).join('')}</div>`:'<p class="helper">No active invitations.</p>'}</section></div>`:''}`;
}

export function bindTeam(context,{notify,refresh}){
  document.querySelector('[data-invite-member]')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),values=Object.fromEntries(new FormData(form));button.disabled=true;button.textContent='Sending…';try{await inviteWorkspaceMember({workspaceId:context.workspace.id,email:values.email,role:values.role,expiresInDays:Number(values.expires)});form.reset();notify('Invitation sent',`A secure invitation was sent to ${values.email}.`);await refresh()}catch(error){notify('Invitation not sent',error.message)}finally{button.disabled=false;button.textContent='Send invitation'}});
  document.querySelectorAll('[data-member-role]').forEach(select=>select.addEventListener('change',async()=>{const previous=cache.members.find(member=>member.user_id===select.dataset.memberRole)?.role;select.disabled=true;try{await updateWorkspaceMemberRole(context.workspace.id,select.dataset.memberRole,select.value);notify('Role updated',`The member is now ${roleName(select.value)}.`);await refresh()}catch(error){select.value=previous;notify('Role not updated',error.message)}finally{select.disabled=false}}));
  document.querySelectorAll('[data-remove-member]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Remove this member from the workspace? Their access will end immediately.'))return;button.disabled=true;try{await removeWorkspaceMember(context.workspace.id,button.dataset.removeMember);notify('Member removed','Workspace access has been revoked.');await refresh()}catch(error){notify('Member not removed',error.message)}finally{button.disabled=false}}));
  document.querySelectorAll('[data-revoke-invite]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Revoke this invitation? The link will stop working immediately.'))return;button.disabled=true;try{await revokeWorkspaceInvitation(context.workspace.id,button.dataset.revokeInvite);notify('Invitation revoked','The invitation link can no longer be accepted.');await refresh()}catch(error){notify('Invitation not revoked',error.message)}finally{button.disabled=false}}));
}
