export function roi(totalBenefits,totalCosts){return totalCosts===0?null:(totalBenefits-totalCosts)/totalCosts}
export function npv(rate,cashFlows){if(rate<=-1)throw new RangeError('Discount rate must be greater than -1');return cashFlows.reduce((value,cashFlow,period)=>value+cashFlow/(1+rate)**period,0)}
export function payback(cashFlows){let cumulative=0;for(let period=0;period<cashFlows.length;period++){const previous=cumulative;cumulative+=cashFlows[period];if(cumulative>=0){if(period===0)return 0;const flow=cashFlows[period];return flow===0?period:period-1+Math.abs(previous)/flow}}return null}
export function evm({pv,ev,ac,bac,forecastAtCompletion=null}){const safe=(numerator,denominator)=>denominator===0?null:numerator/denominator,cpi=safe(ev,ac),spi=safe(ev,pv),eacCpi=cpi===null||cpi===0?null:bac/cpi,eacCombined=cpi===null||spi===null||cpi*spi===0?null:ac+(bac-ev)/(cpi*spi),eacBottomUp=forecastAtCompletion===null?null:Number(forecastAtCompletion),eac=eacBottomUp??eacCpi,etc=eac===null?null:eac-ac;return{cv:ev-ac,sv:ev-pv,cpi,spi,eac,eacCpi,eacCombined,eacBottomUp,etc,vac:eac===null?null:bac-eac,tcpiBac:safe(bac-ev,bac-ac),tcpiEac:eac===null?null:safe(bac-ev,eac-ac)}}
export function riskScore(probability,impact){if(probability<0||impact<0)throw new RangeError('Risk inputs cannot be negative');return probability*impact}
export function weightedScore(criteria){const weightTotal=criteria.reduce((sum,item)=>sum+item.weight,0);if(weightTotal===0)return null;return criteria.reduce((sum,item)=>sum+item.score*item.weight,0)/weightTotal}
function dependencyWeight(edge,from,to){const lag=Number(edge.lag)||0;switch(edge.type||'FS'){case'SS':return lag;case'FF':return from.duration-to.duration+lag;case'SF':return-to.duration+lag;default:return from.duration+lag}}
export function calculateCpm(tasks,dependencies){const byId=new Map(tasks.map(t=>[t.id,{...t,duration:Number(t.duration)||0,es:0,ef:0,ls:0,lf:0,float:0}])),incoming=new Map(tasks.map(t=>[t.id,[]])),outgoing=new Map(tasks.map(t=>[t.id,[]]));for(const raw of dependencies){const edge={...raw,type:raw.type||'FS',lag:Number(raw.lag)||0};if(!['FS','SS','FF','SF'].includes(edge.type))throw new Error(`Unsupported dependency type: ${edge.type}`);if(!byId.has(edge.from)||!byId.has(edge.to))throw new Error('Dependency references an unknown task');if(edge.from===edge.to)throw new Error('An activity cannot depend on itself');incoming.get(edge.to).push(edge);outgoing.get(edge.from).push(edge)}const queue=tasks.filter(t=>incoming.get(t.id).length===0).map(t=>t.id),order=[];while(queue.length){const id=queue.shift();order.push(id);for(const edge of outgoing.get(id))if(incoming.get(edge.to).every(parent=>order.includes(parent.from)))queue.push(edge.to)}if(order.length!==tasks.length)throw new Error('Dependency cycle detected');for(const id of order){const task=byId.get(id);task.es=Math.max(0,...incoming.get(id).map(edge=>byId.get(edge.from).es+dependencyWeight(edge,byId.get(edge.from),task)));task.ef=task.es+task.duration}const finish=Math.max(0,...[...byId.values()].map(t=>t.ef));for(const id of [...order].reverse()){const task=byId.get(id);task.ls=outgoing.get(id).length?Math.min(...outgoing.get(id).map(edge=>byId.get(edge.to).ls-dependencyWeight(edge,task,byId.get(edge.to)))):finish-task.duration;task.lf=task.ls+task.duration;task.float=task.ls-task.es}return{duration:finish,tasks:order.map(id=>byId.get(id)),critical:order.filter(id=>Math.abs(byId.get(id).float)<1e-9)}}
export function pert({optimistic,mostLikely,pessimistic}){for(const value of [optimistic,mostLikely,pessimistic])if(Number(value)<0)throw new RangeError('PERT estimates cannot be negative');if(Number(optimistic)>Number(mostLikely)||Number(mostLikely)>Number(pessimistic))throw new RangeError('PERT estimates must satisfy optimistic ≤ most likely ≤ pessimistic');return{expected:(Number(optimistic)+4*Number(mostLikely)+Number(pessimistic))/6,variance:((Number(pessimistic)-Number(optimistic))/6)**2}}
export function addWorkingDays(start,duration,{workingWeekdays=[1,2,3,4,5],nonWorkingDates=[]}={}){const date=new Date(`${start}T00:00:00Z`);if(Number.isNaN(date.getTime()))return null;const blocked=new Set(nonWorkingDates),isWorking=value=>workingWeekdays.includes(value.getUTCDay())&&!blocked.has(value.toISOString().slice(0,10));let remaining=Math.max(0,Math.ceil(Number(duration)||0));while(!isWorking(date))date.setUTCDate(date.getUTCDate()+1);while(remaining>0){date.setUTCDate(date.getUTCDate()+1);if(isWorking(date))remaining--}return date.toISOString().slice(0,10)}
export function scheduleVariance(tasks,baselineTasks=[]){const baseline=new Map(baselineTasks.map(task=>[task.id||task.activity_code,task]));return tasks.map(task=>{const prior=baseline.get(task.id)||baseline.get(task.code),priorStart=prior?.plannedStart||prior?.planned_start||null,priorFinish=prior?.plannedFinish||prior?.planned_finish||null,finishVariance=prior&&task.plannedFinish&&priorFinish?Math.round((new Date(task.plannedFinish)-new Date(priorFinish))/86400000):null;return{id:task.id,baselineStart:priorStart,baselineFinish:priorFinish,currentStart:task.plannedStart||null,currentFinish:task.plannedFinish||null,finishVariance,slipped:finishVariance!==null&&finishVariance>0}})}
