import {PUBLIC_PM_STAGE,pricingPlans,planPrice,pert,readiness,primaryCta} from '/project-management/marketing-config.mjs';
import {page,track,attribution} from '/project-management/analytics.mjs';
import {roi,npv,evm,riskScore} from '/lib/calculators.mjs';

const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)],number=value=>Number(value)||0;
page(document.body.dataset.page||'product',location.pathname);
document.documentElement.dataset.stage=PUBLIC_PM_STAGE;
$$('[data-primary-cta]').forEach(link=>{const cta=primaryCta();link.textContent=cta.label;link.href=cta.href;link.addEventListener('click',()=>track('pm_primary_cta_clicked',{cta_id:link.dataset.primaryCta||'primary',page_type:document.body.dataset.page||'product',destination:cta.href,stage:PUBLIC_PM_STAGE}))});
$$('[data-track-cta]').forEach(link=>link.addEventListener('click',()=>track('pm_primary_cta_clicked',{cta_id:link.dataset.trackCta,page_type:document.body.dataset.page||'product',destination:link.getAttribute('href'),stage:PUBLIC_PM_STAGE})));

const menu=$('[data-menu]'),nav=$('[data-marketing-nav]');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});

let billing='annual';function updatePricing(){const seats=Math.max(1,Math.min(500,number($('[data-seat-count]')?.value)||1));$$('[data-price]').forEach(node=>{const plan=pricingPlans.find(item=>item.id===node.dataset.price),total=planPrice(plan,billing,seats);node.textContent=total===null?'Custom':total===0?'$0':`$${total.toLocaleString()}`});$$('[data-price-period]').forEach(node=>node.textContent=billing==='annual'?'/ month, billed annually':'/ month');$('[data-seat-copy]')&&($('[data-seat-copy]').textContent=`${seats} paid seat${seats===1?'':'s'} · exact-seat billing`);track('pm_pricing_seat_calculated',{plan_id:'all',billing_period:billing,seat_count:seats})}
$$('[data-billing]').forEach(button=>button.addEventListener('click',()=>{billing=button.dataset.billing;$$('[data-billing]').forEach(item=>item.classList.toggle('active',item===button));updatePricing()}));$('[data-seat-count]')?.addEventListener('input',updatePricing);if($('[data-price]')){updatePricing();track('pm_pricing_viewed',{billing_period:billing,referrer_page:document.referrer?new URL(document.referrer).pathname:'direct'})}

function result(form,html){const output=form.querySelector('[data-result]');output.innerHTML=html;output.hidden=false}
$$('[data-calculator]').forEach(form=>{let started=false;form.addEventListener('input',()=>{if(!started){track('pm_calculator_started',{calculator_id:form.dataset.calculator});started=true}});form.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form)),id=form.dataset.calculator;if(id==='evm'){const x=evm({pv:number(values.pv),ev:number(values.ev),ac:number(values.ac),bac:number(values.bac)});result(form,`<strong>CPI ${x.cpi?.toFixed(2)??'—'} · SPI ${x.spi?.toFixed(2)??'—'}</strong><span>CV ${x.cv.toLocaleString()} · SV ${x.sv.toLocaleString()} · EAC ${x.eac?.toLocaleString(undefined,{maximumFractionDigits:0})??'—'}</span>`)}else if(id==='financial'){const flows=String(values.cashFlows).split(',').map(number);let present;try{present=npv(number(values.rate)/100,flows)}catch{present=null}const returnValue=roi(number(values.benefits),number(values.costs));result(form,`<strong>ROI ${returnValue===null?'—':(returnValue*100).toFixed(1)+'%'} · NPV ${present===null?'—':present.toLocaleString(undefined,{maximumFractionDigits:0})}</strong><span>Based only on the values and discount rate entered.</span>`)}else if(id==='pert'){const estimate=pert(values),deviation=(number(values.pessimistic)-number(values.optimistic))/6;result(form,`<strong>PERT estimate ${estimate.toFixed(1)} units</strong><span>Standard deviation ${deviation.toFixed(1)}. Use the same unit for all three inputs.</span>`)}else if(id==='risk'){const score=riskScore(number(values.probability),number(values.impact));result(form,`<strong>Risk score ${score}</strong><span>${score>=16?'High exposure':score>=8?'Moderate exposure':'Lower exposure'} on this 5 × 5 scale.</span>`)}else{const controls=$$('input[type="checkbox"]',form),score=Math.round(controls.filter(input=>input.checked).length/controls.length*100);result(form,`<strong>Readiness ${score}%</strong><span>${score<50?'Strengthen initiation before committing major delivery resources.':score<80?'A credible start; close the remaining control gaps.':'Strong initiation coverage; keep approvals and evidence current.'}</span>`)}track('pm_calculator_completed',{calculator_id:id})})});

const demoSteps=$$('[data-demo-step]');function showDemo(index){demoSteps.forEach((step,i)=>step.hidden=i!==index);$$('[data-demo-nav]').forEach((button,i)=>button.classList.toggle('active',i===index));track('pm_demo_step_viewed',{step_id:demoSteps[index]?.dataset.demoStep||'',step_index:index+1});if(index===demoSteps.length-1)track('pm_demo_completed',{steps_completed:demoSteps.length})}$$('[data-demo-nav]').forEach((button,index)=>button.addEventListener('click',()=>showDemo(index)));if(demoSteps.length){track('pm_demo_started',{entry_page:location.pathname});showDemo(0)}

$$('[data-template]').forEach(card=>{track('pm_template_viewed',{template_id:card.dataset.template,category:card.dataset.category});card.querySelector('a')?.addEventListener('click',()=>track('pm_template_use_clicked',{template_id:card.dataset.template,auth_state:'anonymous'}))});

$$('[data-lead-form]').forEach(form=>{for(const [key,value] of Object.entries(attribution())){const input=document.createElement('input');input.type='hidden';input.name=key;input.value=value;form.append(input)}form.addEventListener('submit',()=>{const eventName=form.dataset.leadForm==='design-partner'?'pm_design_partner_submitted':form.dataset.leadForm==='enterprise'?'pm_enterprise_lead_submitted':'pm_waitlist_submitted';track(eventName,{source_page:location.pathname,role_category:form.elements.role?.value||'unspecified',team_size_bucket:form.elements.team_size?.value||'unspecified',industry_category:form.elements.industry?.value||'unspecified'})})});
