import {z} from 'zod';
import {adminClient,bearerToken,requireMethod,sendJson} from '../../_lib/server.js';
import {projectExportFilename,renderProjectPack} from '../../../lib/project-export.mjs';

const schema=z.object({projectId:z.string().uuid(),format:z.enum(['json','csv','txt','pdf'])}).strict();
export default async function handler(req,res){
  if(!requireMethod(req,res))return;if(Number(req.headers['content-length']||0)>8192)return sendJson(res,413,{error:'payload_too_large'});
  const token=bearerToken(req);if(!token)return sendJson(res,401,{error:'authentication_required'});
  const parsed=schema.safeParse(req.body);if(!parsed.success)return sendJson(res,400,{error:'invalid_request'});
  try{
    const db=adminClient(),{data:{user},error:userError}=await db.auth.getUser(token);if(userError||!user)return sendJson(res,401,{error:'invalid_session'});
    const {data:project,error:projectError}=await db.from('projects').select('id,workspace_id,title,code,data,version,updated_at').eq('id',parsed.data.projectId).is('archived_at',null).maybeSingle();if(projectError)throw projectError;if(!project)return sendJson(res,404,{error:'project_not_found'});
    const {data:membership}=await db.from('workspace_members').select('role').eq('workspace_id',project.workspace_id).eq('user_id',user.id).maybeSingle();if(!membership)return sendJson(res,403,{error:'permission_denied'});
    const [{data:workspace},{data:executionSet},{data:controlSet},{data:reports},{data:reviews},{data:planningSet},{data:scheduleSet},{data:costSet}]=await Promise.all([db.from('workspaces').select('id,name').eq('id',project.workspace_id).single(),db.from('execution_control_sets').select('id,current_version,settings').eq('project_id',project.id).maybeSingle(),db.from('project_control_sets').select('id,current_version,risk_plan').eq('project_id',project.id).maybeSingle(),db.from('project_status_reports').select('report_date,overall_health,content,metrics,published_at').eq('project_id',project.id).order('report_date',{ascending:false}),db.from('governance_reviews').select('review_code,review_type,title,owner_name,status,scheduled_date,criteria,evidence,recommendation,decision_comments,decided_at').eq('project_id',project.id).order('created_at'),db.from('core_planning_sets').select('id,current_version,status').eq('project_id',project.id).maybeSingle(),db.from('schedule_control_sets').select('id,current_version,status').eq('project_id',project.id).maybeSingle(),db.from('cost_control_sets').select('id,current_version,status').eq('project_id',project.id).maybeSingle()]);
    let iterations=[],workItems=[];if(executionSet){const {data:version}=await db.from('execution_versions').select('id').eq('execution_set_id',executionSet.id).eq('version',executionSet.current_version).maybeSingle();if(version){const [iterationResult,workResult]=await Promise.all([db.from('delivery_iterations').select('*').eq('execution_version_id',version.id).order('sort_order'),db.from('delivery_work_items').select('*').eq('execution_version_id',version.id).order('sort_order')]);iterations=iterationResult.data||[];workItems=workResult.data||[]}}
    let risks=[],issues=[],changes=[];if(controlSet){const [riskResult,issueResult,changeResult]=await Promise.all([db.from('project_risks').select('*').eq('control_set_id',controlSet.id).order('sort_order'),db.from('project_issues').select('*').eq('control_set_id',controlSet.id).order('sort_order'),db.from('change_requests').select('*').eq('project_id',project.id).order('created_at')]);risks=riskResult.data||[];issues=issueResult.data||[];changes=changeResult.data||[]}
    let planning={},schedule={},cost={};if(planningSet){const {data:version}=await db.from('core_planning_versions').select('*').eq('planning_set_id',planningSet.id).eq('version',planningSet.current_version).maybeSingle();if(version){const [requirementResult,wbsResult]=await Promise.all([db.from('project_requirements').select('*').eq('planning_version_id',version.id).order('sort_order'),db.from('wbs_nodes').select('*').eq('planning_version_id',version.id).order('sort_order')]);planning={status:planningSet.status,version:planningSet.current_version,masterPlan:version.master_plan,scopeStatement:version.scope_statement,subsidiaryPlans:version.subsidiary_plans,requirements:requirementResult.data||[],wbs:wbsResult.data||[]}}}if(scheduleSet){const {data:version}=await db.from('schedule_versions').select('*').eq('schedule_set_id',scheduleSet.id).eq('version',scheduleSet.current_version).maybeSingle();if(version){const [taskResult,dependencyResult]=await Promise.all([db.from('schedule_tasks').select('*').eq('schedule_version_id',version.id).order('sort_order'),db.from('schedule_dependencies').select('*').eq('schedule_version_id',version.id)]);schedule={status:scheduleSet.status,version:scheduleSet.current_version,settings:version.settings,calendar:version.calendar,tasks:taskResult.data||[],dependencies:dependencyResult.data||[]}}}if(costSet){const {data:version}=await db.from('cost_versions').select('*').eq('cost_set_id',costSet.id).eq('version',costSet.current_version).maybeSingle();if(version){const [itemResult,cashResult]=await Promise.all([db.from('cost_items').select('*').eq('cost_version_id',version.id).order('sort_order'),db.from('cash_flow_entries').select('*').eq('cost_version_id',version.id).order('period_date')]);cost={status:costSet.status,version:costSet.current_version,settings:version.settings,items:itemResult.data||[],cashFlow:cashResult.data||[]}}}
    const normalizedProject={...project.data,id:project.id,title:project.title,code:project.code,version:project.version,updatedAt:project.updated_at},pack={exportedAt:new Date().toISOString(),workspace,project:normalizedProject,planning,schedule,cost,execution:{version:executionSet?.current_version||0,settings:executionSet?.settings||{},iterations:iterations.map(item=>({code:item.iteration_code,name:item.name,type:item.iteration_type,status:item.status,goal:item.goal,startDate:item.start_date,endDate:item.end_date,capacity:Number(item.capacity),plannedPoints:Number(item.planned_points),completedPoints:Number(item.completed_points),reviewOutcome:item.review_outcome,retrospective:item.retrospective})),workItems:workItems.map(item=>({code:item.item_code,title:item.title,type:item.item_type,status:item.status,iterationCode:item.iteration_code,requirement:item.requirement_ref,wbs:item.wbs_ref,owner:item.owner_name,priority:item.priority,estimate:Number(item.estimate),percentComplete:Number(item.percent_complete),acceptanceCriteria:item.acceptance_criteria,evidence:item.evidence,blocker:item.blocker,dueDate:item.due_date})),reviews:(reviews||[]).map(item=>({code:item.review_code,type:item.review_type,title:item.title,owner:item.owner_name,status:item.status,scheduledDate:item.scheduled_date,criteria:item.criteria,evidence:item.evidence,recommendation:item.recommendation,decisionComments:item.decision_comments,decidedAt:item.decided_at}))},controls:{version:controlSet?.current_version||0,riskPlan:controlSet?.risk_plan||{},risks:risks.map(item=>({code:item.risk_code,event:item.event,owner:item.owner_name,status:item.status,probability:Number(item.probability),impactScore:Number(item.impact_score),linkedArtifact:item.linked_artifact})),issues:issues.map(item=>({code:item.issue_code,title:item.title,owner:item.owner_name,status:item.status,severity:item.severity,linkedArtifact:item.linked_artifact})),changes:changes.map(item=>({code:item.request_code,title:item.title,requester:item.requester,status:item.status,type:item.change_type,costImpact:Number(item.cost_impact)}))},reports:(reports||[]).map(item=>({...item.content,date:item.report_date,health:item.overall_health,metrics:item.metrics,publishedAt:item.published_at}))};
    const rendered=await renderProjectPack(pack,parsed.data.format);await db.from('audit_events').insert({workspace_id:project.workspace_id,project_id:project.id,actor_user_id:user.id,action:'exported',entity_type:'project_pack',entity_id:project.id,metadata:{format:parsed.data.format,execution_version:executionSet?.current_version||0,control_version:controlSet?.current_version||0}});
    res.setHeader('Content-Type',rendered.contentType);res.setHeader('Content-Disposition',`attachment; filename="${projectExportFilename(project,parsed.data.format)}"`);res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');return res.status(200).send(rendered.bytes);
  }catch(error){console.error('project_export_failed',error?.message);return sendJson(res,500,{error:'export_failed',message:error?.message||'Unable to generate project pack'})}
}
