import {access,readFile} from 'node:fs/promises';

const pages=[
  'index.html','start-a-project/index.html','project-management/index.html','pm/index.html','pm/login/index.html','share/index.html',
  ...['features','pricing','demo','early-access','templates','resources','tools','solutions','compare','security','privacy','terms','changelog'].map(route=>`project-management/${route}/index.html`)
];
const required=['.env.example','styles.css','app.js','robots.txt','sitemap.xml','lib/calculators.mjs','lib/email-template.mjs','lib/controlled-document-export.mjs','lib/resource-catalog.mjs','lib/resource-tools.mjs','resources/resource.css','resources/resource.js','project-management/marketing-config.mjs','project-management/entitlements.mjs','project-management/analytics.mjs','project-management/marketing.js','project-management/marketing.css','pm/pm.js','pm/backend.js','pm/auth.js','pm/account.js','pm/studio.js','pm/team.js','pm/pm.css','share/share.js','api/v1/forms/submit.js','api/v1/messages/send.js','api/v1/resources/claim.js','api/v1/workspace/invitations.js','api/v1/documents/export.js','api/v1/documents/shares.js','api/v1/documents/shared.js','supabase/migrations/202609060001_pm_foundation.sql','supabase/migrations/202609060002_integrations_communications.sql','supabase/migrations/202609070007_workspace_invitations.sql','supabase/migrations/202609070008_controlled_documents.sql','supabase/migrations/202609070009_document_exports_and_shares.sql','supabase/migrations/202609080010_resource_growth_engine.sql','supabase/migrations/202609080012_phase2_initiation.sql','assets/images/hero-architecture.jpg','assets/images/studio-drawings.jpg','assets/images/project-duplex.jpg','assets/images/project-commercial.jpg','assets/images/project-interior.jpg'];
required.push('lib/resource-assets.mjs','supabase/migrations/202609080011_service_workspace_read.sql','seo/config.mjs','seo/render.mjs','404.html','site.webmanifest','favicon.svg','favicon-32.png','apple-touch-icon.png','assets/images/og-arkhimar-consult.jpg','assets/images/og-arkhimar-pm.png');
const errors=[];
for(const file of [...pages,...required]){try{await access(file)}catch{errors.push(`Missing ${file}`)}}
for(const page of pages){const html=await readFile(page,'utf8');if(!/<title>[^<]+<\/title>/.test(html))errors.push(`${page}: missing title`);if(!/<meta name="description"/.test(html))errors.push(`${page}: missing description`);if(!/<main(?:\s|>)/.test(html))errors.push(`${page}: missing main landmark`);if(page.startsWith('project-management/')&&!/<link rel="canonical"/.test(html))errors.push(`${page}: missing canonical URL`)}
const enquiry=await readFile('start-a-project/index.html','utf8');if(!/enctype="multipart\/form-data"/.test(enquiry))errors.push('Project form must use multipart encoding');if(!/<input[^>]+type="file"[^>]+multiple/.test(enquiry))errors.push('Project form must support multiple attachments');
const pm=await readFile('pm/index.html','utf8');if(!/<meta name="robots" content="noindex,nofollow">/.test(pm))errors.push('Private PM route must be noindex');if(!/data-other-industry hidden/.test(pm))errors.push('Other project type must have an optional specification field');
const migration=await readFile('supabase/migrations/202609060001_pm_foundation.sql','utf8');for(const contract of ['enable row level security','project-documents','audit_events','bootstrap_workspace','projects_manager_insert','projects_manager_update','project_files_member_read','project_files_contributor_insert','revoke insert,update,delete on public.audit_events'])if(!migration.includes(contract))errors.push(`Migration missing ${contract}`);
const integrationsMigration=await readFile('supabase/migrations/202609060002_integrations_communications.sql','utf8');for(const contract of ['workspace_brand_settings','message_templates','outbound_messages','api_keys','form_submissions','authorize_api_key_request','workspace-brand-assets','enable row level security'])if(!integrationsMigration.includes(contract))errors.push(`Integration migration missing ${contract}`);
const auth=await readFile('pm/auth.js','utf8');for(const contract of ['signInWithPassword','signUp','resetPasswordForEmail','PASSWORD_RECOVERY','updateUser','mfaRequirement','verifyMfaCode'])if(!auth.includes(contract))errors.push(`Authentication flow missing ${contract}`);
const account=await readFile('pm/account.js','utf8');for(const contract of ["factorType:'totp'",'challengeAndVerify','unenroll',"scope:'others'"])if(!account.includes(contract))errors.push(`Account security missing ${contract}`);
const formApi=await readFile('api/v1/forms/submit.js','utf8');for(const contract of ['x-api-key','authorize_api_key_request','schema.safeParse'])if(!formApi.includes(contract))errors.push(`Form API missing ${contract}`);
const emailApi=await readFile('api/v1/messages/send.js','utf8');for(const contract of ['auth.getUser','Idempotency-Key','RESEND_API_KEY','permission_denied'])if(!emailApi.includes(contract))errors.push(`Email API missing ${contract}`);
const invitationApi=await readFile('api/v1/workspace/invitations.js','utf8');for(const contract of ['auth.getUser','workspace_invitations','Idempotency-Key','owner_required_for_admin_invite'])if(!invitationApi.includes(contract))errors.push(`Invitation API missing ${contract}`);
const controlledMigration=await readFile('supabase/migrations/202609070008_controlled_documents.sql','utf8');for(const contract of ['controlled_documents','controlled_document_versions','protect_approved_document_version','create_controlled_document','revise_controlled_document','transition_controlled_document','enable row level security'])if(!controlledMigration.includes(contract))errors.push(`Controlled document migration missing ${contract}`);
const shareMigration=await readFile('supabase/migrations/202609070009_document_exports_and_shares.sql','utf8');for(const contract of ['controlled_document_shares','token_hash','expires_at','max_downloads','revoked_at','enable row level security'])if(!shareMigration.includes(contract))errors.push(`Document share migration missing ${contract}`);
const growthMigration=await readFile('supabase/migrations/202609080010_resource_growth_engine.sql','utf8');for(const contract of ['resource_leads','resource_import_events','import_resource_draft','enable row level security','Project manager permission required','Resource is not available for import'])if(!growthMigration.includes(contract))errors.push(`Growth migration missing ${contract}`);
const serviceWorkspaceMigration=await readFile('supabase/migrations/202609080011_service_workspace_read.sql','utf8');if(!/grant select on table public\.workspaces to service_role/i.test(serviceWorkspaceMigration))errors.push('Service workspace migration missing least-privilege read grant');
const initiationMigration=await readFile('supabase/migrations/202609080012_phase2_initiation.sql','utf8');for(const contract of ['business_cases','business_case_options','project_charters','protect_approved_initiation_version','save_business_case','transition_business_case','save_project_charter','transition_project_charter','enable row level security','At least two options are required'])if(!initiationMigration.includes(contract))errors.push(`Initiation migration missing ${contract}`);
const phase5Migration=await readFile('supabase/migrations/202609090015_phase5_project_controls.sql','utf8');for(const contract of ['project_control_sets','control_register_versions','project_risks','project_issues','project_stakeholders','stakeholder_private_notes','change_requests','change_request_history','save_project_controls','transition_change_request','enable row level security'])if(!phase5Migration.includes(contract))errors.push(`Phase 5 migration missing ${contract}`);
const phase5PrivacyMigration=await readFile('supabase/migrations/202609090016_phase5_snapshot_privacy.sql','utf8');for(const contract of ['drop policy if exists control_register_versions_member_read','control_register_versions_manager_read','workspace_role_for'])if(!phase5PrivacyMigration.includes(contract))errors.push(`Phase 5 privacy migration missing ${contract}`);
const phase6Migration=await readFile('supabase/migrations/202609090017_phase6_execution_reporting.sql','utf8');for(const contract of ['execution_control_sets','execution_versions','delivery_iterations','delivery_work_items','governance_reviews','governance_review_history','project_status_reports','save_execution_control','transition_governance_review','publish_status_report','enable row level security'])if(!phase6Migration.includes(contract))errors.push(`Phase 6 migration missing ${contract}`);
const projectExportApi=await readFile('api/v1/projects/export.js','utf8');for(const contract of ['auth.getUser','workspace_members','renderProjectPack','audit_events','private, no-store'])if(!projectExportApi.includes(contract))errors.push(`Project export API missing ${contract}`);
if(!/data-view="execution"/.test(pm))errors.push('PM workspace navigation missing execution and governance view');
const pmBackend=await readFile('pm/backend.js','utf8');for(const contract of ['listControlledDocuments','createControlledDocument','transitionControlledDocument','reviseControlledDocument'])if(!pmBackend.includes(contract))errors.push(`Controlled document client missing ${contract}`);
const sitemap=await readFile('sitemap.xml','utf8');if(sitemap.includes('/pm/'))errors.push('Private PM app must not be in sitemap');
const seoConfig=await readFile('seo/config.mjs','utf8');for(const contract of ['https://www.arkhimar.com','/about','/services','/projects','/how-it-works','/project-management'])if(!seoConfig.includes(contract))errors.push(`SEO config missing ${contract}`);
for(const file of ['dist/about/index.html','dist/services/index.html','dist/projects/index.html','dist/how-it-works/index.html','dist/contact/index.html']){try{const html=await readFile(file,'utf8');if(!/<meta name="robots" content="noindex,nofollow">/.test(html))errors.push(`${file}: preview build must be noindex`)}catch{errors.push(`Missing generated route ${file}`)}}
for(const file of ['dist/resources/index.html','dist/resources/architecture/project-brief-starter-kit/index.html','dist/tools/design-readiness/index.html','dist/tools/project-brief-builder/index.html','dist/project-management/workflow-packs/index.html','dist/project-management/workflow-packs/project-initiation-pack/index.html']){try{const html=await readFile(file,'utf8');if(!/noindex,nofollow/.test(html))errors.push(`${file}: preview build must be noindex`);if(!/<main(?:\s|>)/.test(html))errors.push(`${file}: missing main landmark`)}catch{errors.push(`Missing generated route ${file}`)}}
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`Checked ${pages.length} routes, ${required.length} assets, SEO policy and form contracts.`);
