import {access,readFile} from 'node:fs/promises';

const pages=[
  'index.html','start-a-project/index.html','project-management/index.html','pm/index.html','pm/login/index.html',
  ...['features','pricing','demo','early-access','templates','resources','tools','solutions','compare','security','privacy','terms','changelog'].map(route=>`project-management/${route}/index.html`)
];
const required=['.env.example','styles.css','app.js','robots.txt','sitemap.xml','lib/calculators.mjs','lib/email-template.mjs','project-management/marketing-config.mjs','project-management/entitlements.mjs','project-management/analytics.mjs','project-management/marketing.js','project-management/marketing.css','pm/pm.js','pm/backend.js','pm/auth.js','pm/studio.js','pm/team.js','pm/pm.css','api/v1/forms/submit.js','api/v1/messages/send.js','api/v1/workspace/invitations.js','supabase/migrations/202609060001_pm_foundation.sql','supabase/migrations/202609060002_integrations_communications.sql','supabase/migrations/202609070007_workspace_invitations.sql','assets/images/hero-architecture.jpg','assets/images/studio-drawings.jpg','assets/images/project-duplex.jpg','assets/images/project-commercial.jpg','assets/images/project-interior.jpg'];
required.push('seo/config.mjs','seo/render.mjs','404.html','site.webmanifest','favicon.svg','favicon-32.png','apple-touch-icon.png','assets/images/og-arkhimar-consult.jpg','assets/images/og-arkhimar-pm.png');
const errors=[];
for(const file of [...pages,...required]){try{await access(file)}catch{errors.push(`Missing ${file}`)}}
for(const page of pages){const html=await readFile(page,'utf8');if(!/<title>[^<]+<\/title>/.test(html))errors.push(`${page}: missing title`);if(!/<meta name="description"/.test(html))errors.push(`${page}: missing description`);if(!/<main(?:\s|>)/.test(html))errors.push(`${page}: missing main landmark`);if(page.startsWith('project-management/')&&!/<link rel="canonical"/.test(html))errors.push(`${page}: missing canonical URL`)}
const enquiry=await readFile('start-a-project/index.html','utf8');if(!/enctype="multipart\/form-data"/.test(enquiry))errors.push('Project form must use multipart encoding');if(!/<input[^>]+type="file"[^>]+multiple/.test(enquiry))errors.push('Project form must support multiple attachments');
const pm=await readFile('pm/index.html','utf8');if(!/<meta name="robots" content="noindex,nofollow">/.test(pm))errors.push('Private PM route must be noindex');if(!/data-other-industry hidden/.test(pm))errors.push('Other project type must have an optional specification field');
const migration=await readFile('supabase/migrations/202609060001_pm_foundation.sql','utf8');for(const contract of ['enable row level security','project-documents','audit_events','bootstrap_workspace','projects_manager_insert','projects_manager_update','project_files_member_read','project_files_contributor_insert','revoke insert,update,delete on public.audit_events'])if(!migration.includes(contract))errors.push(`Migration missing ${contract}`);
const integrationsMigration=await readFile('supabase/migrations/202609060002_integrations_communications.sql','utf8');for(const contract of ['workspace_brand_settings','message_templates','outbound_messages','api_keys','form_submissions','authorize_api_key_request','workspace-brand-assets','enable row level security'])if(!integrationsMigration.includes(contract))errors.push(`Integration migration missing ${contract}`);
const auth=await readFile('pm/auth.js','utf8');for(const contract of ['signInWithPassword','signUp','resetPasswordForEmail','PASSWORD_RECOVERY','updateUser'])if(!auth.includes(contract))errors.push(`Authentication flow missing ${contract}`);
const formApi=await readFile('api/v1/forms/submit.js','utf8');for(const contract of ['x-api-key','authorize_api_key_request','schema.safeParse'])if(!formApi.includes(contract))errors.push(`Form API missing ${contract}`);
const emailApi=await readFile('api/v1/messages/send.js','utf8');for(const contract of ['auth.getUser','Idempotency-Key','RESEND_API_KEY','permission_denied'])if(!emailApi.includes(contract))errors.push(`Email API missing ${contract}`);
const invitationApi=await readFile('api/v1/workspace/invitations.js','utf8');for(const contract of ['auth.getUser','workspace_invitations','Idempotency-Key','owner_required_for_admin_invite'])if(!invitationApi.includes(contract))errors.push(`Invitation API missing ${contract}`);
const sitemap=await readFile('sitemap.xml','utf8');if(sitemap.includes('/pm/'))errors.push('Private PM app must not be in sitemap');
const seoConfig=await readFile('seo/config.mjs','utf8');for(const contract of ['https://www.arkhimar.com','/about','/services','/projects','/how-it-works','/project-management'])if(!seoConfig.includes(contract))errors.push(`SEO config missing ${contract}`);
for(const file of ['dist/about/index.html','dist/services/index.html','dist/projects/index.html','dist/how-it-works/index.html','dist/contact/index.html']){try{const html=await readFile(file,'utf8');if(!/<meta name="robots" content="noindex,nofollow">/.test(html))errors.push(`${file}: preview build must be noindex`)}catch{errors.push(`Missing generated route ${file}`)}}
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`Checked ${pages.length} routes, ${required.length} assets, SEO policy and form contracts.`);
