begin;

create table public.schedule_control_sets (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, project_id uuid not null,
  current_version integer not null default 1 check(current_version>0), status text not null default 'draft' check(status in ('draft','baselined','archived')), revision_reference text,
  created_by uuid not null references auth.users(id), updated_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(project_id), unique(id,workspace_id), foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.schedule_versions (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, schedule_set_id uuid not null, version integer not null check(version>0),
  status text not null default 'draft' check(status in ('draft','approved','superseded')), calendar jsonb not null default '{}'::jsonb check(jsonb_typeof(calendar)='object'), settings jsonb not null default '{}'::jsonb check(jsonb_typeof(settings)='object'),
  created_by uuid not null references auth.users(id), approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(schedule_set_id,version), foreign key(schedule_set_id,workspace_id) references public.schedule_control_sets(id,workspace_id) on delete cascade, foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.schedule_tasks (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, schedule_version_id uuid not null references public.schedule_versions(id) on delete cascade,
  activity_code text not null, wbs_ref text not null default '', name text not null check(nullif(trim(name),'') is not null), description text not null default '', activity_type text not null default 'Activity', milestone boolean not null default false,
  duration numeric(12,2) not null default 0 check(duration>=0), effort numeric(12,2) not null default 0 check(effort>=0), planned_start date, planned_finish date, actual_start date, actual_finish date,
  remaining_duration numeric(12,2) not null default 0 check(remaining_duration>=0), percent_complete numeric(5,2) not null default 0 check(percent_complete between 0 and 100), owner_name text not null default '', assigned_resources text not null default '', calendar_ref text not null default 'Project', constraints text not null default '', priority text not null default 'Medium', status text not null default 'Not started', notes text not null default '', cost_account_ref text not null default '', sort_order integer not null default 0,
  unique(schedule_version_id,activity_code), foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.schedule_dependencies (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, schedule_version_id uuid not null references public.schedule_versions(id) on delete cascade,
  predecessor_code text not null, successor_code text not null, dependency_type text not null default 'FS' check(dependency_type in ('FS','SS','FF','SF')), lag numeric(12,2) not null default 0,
  check(predecessor_code<>successor_code), unique(schedule_version_id,predecessor_code,successor_code,dependency_type), foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.schedule_baselines (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, schedule_set_id uuid not null, schedule_version_id uuid not null references public.schedule_versions(id), version integer not null check(version>0), status text not null default 'approved' check(status in ('approved','superseded')),
  name text not null, snapshot jsonb not null check(jsonb_typeof(snapshot)='object'), change_request_id text, supersedes_baseline_id uuid references public.schedule_baselines(id), approved_by uuid not null references auth.users(id), approved_at timestamptz not null default now(),
  unique(schedule_set_id,version), foreign key(schedule_set_id,workspace_id) references public.schedule_control_sets(id,workspace_id) on delete cascade, foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);

create table public.cost_control_sets (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, project_id uuid not null,
  current_version integer not null default 1 check(current_version>0), status text not null default 'draft' check(status in ('draft','baselined','archived')), revision_reference text,
  created_by uuid not null references auth.users(id), updated_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(project_id), unique(id,workspace_id), foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.cost_versions (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, cost_set_id uuid not null, version integer not null check(version>0), status text not null default 'draft' check(status in ('draft','approved','superseded')),
  settings jsonb not null default '{}'::jsonb check(jsonb_typeof(settings)='object'), created_by uuid not null references auth.users(id), approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(cost_set_id,version), foreign key(cost_set_id,workspace_id) references public.cost_control_sets(id,workspace_id) on delete cascade, foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.cost_items (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, cost_version_id uuid not null references public.cost_versions(id) on delete cascade,
  cost_code text not null, cost_account text not null default '', wbs_ref text not null default '', activity_ref text not null default '', description text not null check(nullif(trim(description),'') is not null), vendor text not null default '',
  cost_type text not null default 'Fixed' check(cost_type in ('Fixed','Variable','Recurring')), classification text not null default 'Capital' check(classification in ('Capital','Operating')), record_type text not null default 'Estimate' check(record_type in ('Estimate','Commitment','Actual','Accrual','Forecast')),
  amount numeric(18,2) not null default 0 check(amount>=0), tax_amount numeric(18,2) not null default 0 check(tax_amount>=0), currency text not null default 'NGN', due_date date, invoice_status text not null default 'Not invoiced', sort_order integer not null default 0,
  unique(cost_version_id,cost_code,record_type), foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.cash_flow_entries (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, cost_version_id uuid not null references public.cost_versions(id) on delete cascade,
  period_date date not null, planned numeric(18,2) not null default 0, earned numeric(18,2) not null default 0, actual numeric(18,2) not null default 0, forecast numeric(18,2) not null default 0, payment_milestone text not null default '', invoice_status text not null default '', unique(cost_version_id,period_date),
  foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);
create table public.cost_baselines (
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null, project_id uuid not null, cost_set_id uuid not null, cost_version_id uuid not null references public.cost_versions(id), version integer not null check(version>0), status text not null default 'approved' check(status in ('approved','superseded')),
  name text not null, snapshot jsonb not null check(jsonb_typeof(snapshot)='object'), change_request_id text, supersedes_baseline_id uuid references public.cost_baselines(id), approved_by uuid not null references auth.users(id), approved_at timestamptz not null default now(),
  unique(cost_set_id,version), foreign key(cost_set_id,workspace_id) references public.cost_control_sets(id,workspace_id) on delete cascade, foreign key(project_id,workspace_id) references public.projects(id,workspace_id) on delete cascade
);

create index schedule_tasks_project_idx on public.schedule_tasks(project_id,sort_order); create index schedule_dependencies_version_idx on public.schedule_dependencies(schedule_version_id);
create index schedule_baselines_project_idx on public.schedule_baselines(project_id,version desc); create index cost_items_project_idx on public.cost_items(project_id,sort_order);
create index cash_flow_project_idx on public.cash_flow_entries(project_id,period_date); create index cost_baselines_project_idx on public.cost_baselines(project_id,version desc);
create trigger protect_schedule_versions before update or delete on public.schedule_versions for each row when(old.status in ('approved','superseded')) execute procedure public.protect_approved_planning_records();
create trigger protect_schedule_baselines before update or delete on public.schedule_baselines for each row execute procedure public.protect_approved_planning_records();
create trigger protect_cost_versions before update or delete on public.cost_versions for each row when(old.status in ('approved','superseded')) execute procedure public.protect_approved_planning_records();
create trigger protect_cost_baselines before update or delete on public.cost_baselines for each row execute procedure public.protect_approved_planning_records();

create or replace function public.save_schedule_control(target_project uuid,expected_version integer,calendar_content jsonb,setting_content jsonb,task_items jsonb,dependency_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare target_workspace uuid; actor_role public.workspace_role; artifact public.schedule_control_sets; ver public.schedule_versions; item jsonb;
begin
 if jsonb_typeof(coalesce(calendar_content,'{}'))<>'object' or jsonb_typeof(coalesce(task_items,'[]'))<>'array' or jsonb_typeof(coalesce(dependency_items,'[]'))<>'array' then raise exception 'Invalid schedule payload'; end if;
 select workspace_id into target_workspace from public.projects where id=target_project; actor_role:=public.workspace_role_for(target_workspace); if target_workspace is null or actor_role not in ('owner','admin','project_manager') then raise exception 'Project manager permission required'; end if;
 select * into artifact from public.schedule_control_sets where project_id=target_project for update;
 if artifact.id is null then insert into public.schedule_control_sets(workspace_id,project_id,created_by,updated_by) values(target_workspace,target_project,auth.uid(),auth.uid()) returning * into artifact; insert into public.schedule_versions(workspace_id,project_id,schedule_set_id,version,calendar,settings,created_by) values(target_workspace,target_project,artifact.id,1,calendar_content,setting_content,auth.uid()) returning * into ver;
 else if artifact.current_version<>expected_version then raise exception 'Schedule version conflict'; end if; if artifact.status<>'draft' then raise exception 'Start an authorized schedule revision before editing'; end if; select * into ver from public.schedule_versions where schedule_set_id=artifact.id and version=artifact.current_version; update public.schedule_versions set calendar=calendar_content,settings=setting_content,updated_at=now() where id=ver.id; delete from public.schedule_dependencies where schedule_version_id=ver.id; delete from public.schedule_tasks where schedule_version_id=ver.id; end if;
 for item in select value from jsonb_array_elements(task_items) loop insert into public.schedule_tasks(id,workspace_id,project_id,schedule_version_id,activity_code,wbs_ref,name,description,activity_type,milestone,duration,effort,planned_start,planned_finish,actual_start,actual_finish,remaining_duration,percent_complete,owner_name,assigned_resources,calendar_ref,constraints,priority,status,notes,cost_account_ref,sort_order) values(coalesce(nullif(item->>'id','')::uuid,gen_random_uuid()),target_workspace,target_project,ver.id,item->>'code',coalesce(item->>'wbs',''),item->>'name',coalesce(item->>'description',''),coalesce(item->>'type','Activity'),coalesce((item->>'milestone')::boolean,false),greatest(0,coalesce(nullif(item->>'duration','')::numeric,0)),greatest(0,coalesce(nullif(item->>'effort','')::numeric,0)),nullif(item->>'plannedStart','')::date,nullif(item->>'plannedFinish','')::date,nullif(item->>'actualStart','')::date,nullif(item->>'actualFinish','')::date,greatest(0,coalesce(nullif(item->>'remainingDuration','')::numeric,0)),greatest(0,least(100,coalesce(nullif(item->>'percentComplete','')::numeric,0))),coalesce(item->>'owner',''),coalesce(item->>'resources',''),coalesce(item->>'calendar','Project'),coalesce(item->>'constraints',''),coalesce(item->>'priority','Medium'),coalesce(item->>'status','Not started'),coalesce(item->>'notes',''),coalesce(item->>'costAccount',''),coalesce(nullif(item->>'sortOrder','')::integer,0)); end loop;
 for item in select value from jsonb_array_elements(dependency_items) loop if not exists(select 1 from public.schedule_tasks where schedule_version_id=ver.id and activity_code=item->>'from') or not exists(select 1 from public.schedule_tasks where schedule_version_id=ver.id and activity_code=item->>'to') then raise exception 'Dependency references an unknown task'; end if; insert into public.schedule_dependencies(workspace_id,project_id,schedule_version_id,predecessor_code,successor_code,dependency_type,lag) values(target_workspace,target_project,ver.id,item->>'from',item->>'to',coalesce(item->>'type','FS'),coalesce(nullif(item->>'lag','')::numeric,0)); end loop;
 update public.schedule_control_sets set updated_by=auth.uid(),updated_at=now() where id=artifact.id; insert into public.audit_events(workspace_id,project_id,actor_user_id,action,entity_type,entity_id,metadata) values(target_workspace,target_project,auth.uid(),'saved','schedule_control',artifact.id::text,jsonb_build_object('version',artifact.current_version,'tasks',jsonb_array_length(task_items)));
 return jsonb_build_object('version',artifact.current_version,'status',artifact.status);
end $$;

create or replace function public.save_cost_control(target_project uuid,expected_version integer,setting_content jsonb,cost_items_payload jsonb,cash_flow_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare target_workspace uuid; actor_role public.workspace_role; artifact public.cost_control_sets; ver public.cost_versions; item jsonb;
begin
 if jsonb_typeof(coalesce(setting_content,'{}'))<>'object' or jsonb_typeof(coalesce(cost_items_payload,'[]'))<>'array' or jsonb_typeof(coalesce(cash_flow_payload,'[]'))<>'array' then raise exception 'Invalid cost payload'; end if;
 select workspace_id into target_workspace from public.projects where id=target_project; actor_role:=public.workspace_role_for(target_workspace); if target_workspace is null or actor_role not in ('owner','admin','project_manager') then raise exception 'Project manager permission required'; end if;
 select * into artifact from public.cost_control_sets where project_id=target_project for update;
 if artifact.id is null then insert into public.cost_control_sets(workspace_id,project_id,created_by,updated_by) values(target_workspace,target_project,auth.uid(),auth.uid()) returning * into artifact; insert into public.cost_versions(workspace_id,project_id,cost_set_id,version,settings,created_by) values(target_workspace,target_project,artifact.id,1,setting_content,auth.uid()) returning * into ver;
 else if artifact.current_version<>expected_version then raise exception 'Cost version conflict'; end if; if artifact.status<>'draft' then raise exception 'Start an authorized cost revision before editing'; end if; select * into ver from public.cost_versions where cost_set_id=artifact.id and version=artifact.current_version; update public.cost_versions set settings=setting_content,updated_at=now() where id=ver.id; delete from public.cost_items where cost_version_id=ver.id; delete from public.cash_flow_entries where cost_version_id=ver.id; end if;
 for item in select value from jsonb_array_elements(cost_items_payload) loop insert into public.cost_items(id,workspace_id,project_id,cost_version_id,cost_code,cost_account,wbs_ref,activity_ref,description,vendor,cost_type,classification,record_type,amount,tax_amount,currency,due_date,invoice_status,sort_order) values(coalesce(nullif(item->>'id','')::uuid,gen_random_uuid()),target_workspace,target_project,ver.id,item->>'code',coalesce(item->>'account',''),coalesce(item->>'wbs',''),coalesce(item->>'activity',''),item->>'description',coalesce(item->>'vendor',''),coalesce(item->>'costType','Fixed'),coalesce(item->>'classification','Capital'),coalesce(item->>'recordType','Estimate'),greatest(0,coalesce(nullif(item->>'amount','')::numeric,0)),greatest(0,coalesce(nullif(item->>'tax','')::numeric,0)),coalesce(item->>'currency',setting_content->>'currency','NGN'),nullif(item->>'dueDate','')::date,coalesce(item->>'invoiceStatus','Not invoiced'),coalesce(nullif(item->>'sortOrder','')::integer,0)); end loop;
 for item in select value from jsonb_array_elements(cash_flow_payload) loop insert into public.cash_flow_entries(id,workspace_id,project_id,cost_version_id,period_date,planned,earned,actual,forecast,payment_milestone,invoice_status) values(coalesce(nullif(item->>'id','')::uuid,gen_random_uuid()),target_workspace,target_project,ver.id,(item->>'date')::date,coalesce(nullif(item->>'planned','')::numeric,0),coalesce(nullif(item->>'earned','')::numeric,0),coalesce(nullif(item->>'actual','')::numeric,0),coalesce(nullif(item->>'forecast','')::numeric,0),coalesce(item->>'milestone',''),coalesce(item->>'invoiceStatus','')); end loop;
 update public.cost_control_sets set updated_by=auth.uid(),updated_at=now() where id=artifact.id; insert into public.audit_events(workspace_id,project_id,actor_user_id,action,entity_type,entity_id,metadata) values(target_workspace,target_project,auth.uid(),'saved','cost_control',artifact.id::text,jsonb_build_object('version',artifact.current_version,'cost_items',jsonb_array_length(cost_items_payload)));
 return jsonb_build_object('version',artifact.current_version,'status',artifact.status);
end $$;

create or replace function public.approve_delivery_baseline(target_project uuid,baseline_type text,expected_version integer,baseline_name text) returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.schedule_control_sets; sv public.schedule_versions; c public.cost_control_sets; cv public.cost_versions; actor_role public.workspace_role; next_version integer; prior uuid; snap jsonb;
begin
 if baseline_type='schedule' then select * into s from public.schedule_control_sets where project_id=target_project for update; actor_role:=public.workspace_role_for(s.workspace_id); if s.id is null or s.current_version<>expected_version or s.status<>'draft' then raise exception 'Schedule version conflict or no draft'; end if; if actor_role not in ('owner','admin') then raise exception 'Owner or admin approval required'; end if; select * into sv from public.schedule_versions where schedule_set_id=s.id and version=s.current_version; if not exists(select 1 from public.schedule_tasks where schedule_version_id=sv.id) then raise exception 'At least one schedule task is required'; end if; next_version:=coalesce((select max(version)+1 from public.schedule_baselines where schedule_set_id=s.id),1); select id into prior from public.schedule_baselines where schedule_set_id=s.id and status='approved' order by version desc limit 1; if prior is not null then update public.schedule_baselines set status='superseded' where id=prior; end if; snap:=jsonb_build_object('calendar',sv.calendar,'settings',sv.settings,'tasks',coalesce((select jsonb_agg(to_jsonb(t) order by sort_order) from public.schedule_tasks t where schedule_version_id=sv.id),'[]'),'dependencies',coalesce((select jsonb_agg(to_jsonb(d)) from public.schedule_dependencies d where schedule_version_id=sv.id),'[]')); update public.schedule_versions set status='approved',approved_by=auth.uid(),approved_at=now() where id=sv.id; insert into public.schedule_baselines(workspace_id,project_id,schedule_set_id,schedule_version_id,version,name,snapshot,change_request_id,supersedes_baseline_id,approved_by) values(s.workspace_id,s.project_id,s.id,sv.id,next_version,baseline_name,snap,s.revision_reference,prior,auth.uid()); update public.schedule_control_sets set status='baselined',revision_reference=null,updated_by=auth.uid(),updated_at=now() where id=s.id;
 elsif baseline_type='cost' then select * into c from public.cost_control_sets where project_id=target_project for update; actor_role:=public.workspace_role_for(c.workspace_id); if c.id is null or c.current_version<>expected_version or c.status<>'draft' then raise exception 'Cost version conflict or no draft'; end if; if actor_role not in ('owner','admin') then raise exception 'Owner or admin approval required'; end if; select * into cv from public.cost_versions where cost_set_id=c.id and version=c.current_version; if not exists(select 1 from public.cost_items where cost_version_id=cv.id) then raise exception 'At least one cost item is required'; end if; next_version:=coalesce((select max(version)+1 from public.cost_baselines where cost_set_id=c.id),1); select id into prior from public.cost_baselines where cost_set_id=c.id and status='approved' order by version desc limit 1; if prior is not null then update public.cost_baselines set status='superseded' where id=prior; end if; snap:=jsonb_build_object('settings',cv.settings,'items',coalesce((select jsonb_agg(to_jsonb(i) order by sort_order) from public.cost_items i where cost_version_id=cv.id),'[]'),'cashFlow',coalesce((select jsonb_agg(to_jsonb(f) order by period_date) from public.cash_flow_entries f where cost_version_id=cv.id),'[]')); update public.cost_versions set status='approved',approved_by=auth.uid(),approved_at=now() where id=cv.id; insert into public.cost_baselines(workspace_id,project_id,cost_set_id,cost_version_id,version,name,snapshot,change_request_id,supersedes_baseline_id,approved_by) values(c.workspace_id,c.project_id,c.id,cv.id,next_version,baseline_name,snap,c.revision_reference,prior,auth.uid()); update public.cost_control_sets set status='baselined',revision_reference=null,updated_by=auth.uid(),updated_at=now() where id=c.id;
 else raise exception 'Unknown baseline type'; end if;
 insert into public.audit_events(workspace_id,project_id,actor_user_id,action,entity_type,entity_id,metadata) values(coalesce(s.workspace_id,c.workspace_id),target_project,auth.uid(),'approved',baseline_type||'_baseline',target_project::text,jsonb_build_object('version',next_version)); return jsonb_build_object('version',next_version,'status','baselined');
end $$;

create or replace function public.begin_delivery_revision(target_project uuid,baseline_type text,expected_version integer,change_reference text) returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.schedule_control_sets; sv public.schedule_versions; c public.cost_control_sets; cv public.cost_versions; actor_role public.workspace_role; next_version integer; new_version uuid;
begin
 if nullif(trim(change_reference),'') is null then raise exception 'An approved change or revision authorization reference is required'; end if;
 if baseline_type='schedule' then select * into s from public.schedule_control_sets where project_id=target_project for update; actor_role:=public.workspace_role_for(s.workspace_id); if s.id is null or s.current_version<>expected_version or s.status<>'baselined' then raise exception 'Schedule version conflict or baseline not current'; end if; if actor_role not in ('owner','admin','project_manager') then raise exception 'Project manager permission required'; end if; select * into sv from public.schedule_versions where schedule_set_id=s.id and version=s.current_version; next_version:=s.current_version+1; insert into public.schedule_versions(workspace_id,project_id,schedule_set_id,version,calendar,settings,created_by) values(s.workspace_id,s.project_id,s.id,next_version,sv.calendar,sv.settings,auth.uid()) returning id into new_version; insert into public.schedule_tasks(workspace_id,project_id,schedule_version_id,activity_code,wbs_ref,name,description,activity_type,milestone,duration,effort,planned_start,planned_finish,actual_start,actual_finish,remaining_duration,percent_complete,owner_name,assigned_resources,calendar_ref,constraints,priority,status,notes,cost_account_ref,sort_order) select workspace_id,project_id,new_version,activity_code,wbs_ref,name,description,activity_type,milestone,duration,effort,planned_start,planned_finish,actual_start,actual_finish,remaining_duration,percent_complete,owner_name,assigned_resources,calendar_ref,constraints,priority,status,notes,cost_account_ref,sort_order from public.schedule_tasks where schedule_version_id=sv.id; insert into public.schedule_dependencies(workspace_id,project_id,schedule_version_id,predecessor_code,successor_code,dependency_type,lag) select workspace_id,project_id,new_version,predecessor_code,successor_code,dependency_type,lag from public.schedule_dependencies where schedule_version_id=sv.id; update public.schedule_control_sets set current_version=next_version,status='draft',revision_reference=trim(change_reference),updated_by=auth.uid(),updated_at=now() where id=s.id;
 elsif baseline_type='cost' then select * into c from public.cost_control_sets where project_id=target_project for update; actor_role:=public.workspace_role_for(c.workspace_id); if c.id is null or c.current_version<>expected_version or c.status<>'baselined' then raise exception 'Cost version conflict or baseline not current'; end if; if actor_role not in ('owner','admin','project_manager') then raise exception 'Project manager permission required'; end if; select * into cv from public.cost_versions where cost_set_id=c.id and version=c.current_version; next_version:=c.current_version+1; insert into public.cost_versions(workspace_id,project_id,cost_set_id,version,settings,created_by) values(c.workspace_id,c.project_id,c.id,next_version,cv.settings,auth.uid()) returning id into new_version; insert into public.cost_items(workspace_id,project_id,cost_version_id,cost_code,cost_account,wbs_ref,activity_ref,description,vendor,cost_type,classification,record_type,amount,tax_amount,currency,due_date,invoice_status,sort_order) select workspace_id,project_id,new_version,cost_code,cost_account,wbs_ref,activity_ref,description,vendor,cost_type,classification,record_type,amount,tax_amount,currency,due_date,invoice_status,sort_order from public.cost_items where cost_version_id=cv.id; insert into public.cash_flow_entries(workspace_id,project_id,cost_version_id,period_date,planned,earned,actual,forecast,payment_milestone,invoice_status) select workspace_id,project_id,new_version,period_date,planned,earned,actual,forecast,payment_milestone,invoice_status from public.cash_flow_entries where cost_version_id=cv.id; update public.cost_control_sets set current_version=next_version,status='draft',revision_reference=trim(change_reference),updated_by=auth.uid(),updated_at=now() where id=c.id;
 else raise exception 'Unknown baseline type'; end if;
 insert into public.audit_events(workspace_id,project_id,actor_user_id,action,entity_type,entity_id,metadata) values(coalesce(s.workspace_id,c.workspace_id),target_project,auth.uid(),'revision_started',baseline_type||'_baseline',target_project::text,jsonb_build_object('version',next_version,'authorization',trim(change_reference))); return jsonb_build_object('version',next_version,'status','draft');
end $$;

alter table public.schedule_control_sets enable row level security; alter table public.schedule_versions enable row level security; alter table public.schedule_tasks enable row level security; alter table public.schedule_dependencies enable row level security; alter table public.schedule_baselines enable row level security; alter table public.cost_control_sets enable row level security; alter table public.cost_versions enable row level security; alter table public.cost_items enable row level security; alter table public.cash_flow_entries enable row level security; alter table public.cost_baselines enable row level security;
create policy schedule_control_sets_member_read on public.schedule_control_sets for select to authenticated using(public.is_workspace_member(workspace_id)); create policy schedule_versions_member_read on public.schedule_versions for select to authenticated using(public.is_workspace_member(workspace_id)); create policy schedule_tasks_member_read on public.schedule_tasks for select to authenticated using(public.is_workspace_member(workspace_id)); create policy schedule_dependencies_member_read on public.schedule_dependencies for select to authenticated using(public.is_workspace_member(workspace_id)); create policy schedule_baselines_member_read on public.schedule_baselines for select to authenticated using(public.is_workspace_member(workspace_id)); create policy cost_control_sets_member_read on public.cost_control_sets for select to authenticated using(public.is_workspace_member(workspace_id)); create policy cost_versions_member_read on public.cost_versions for select to authenticated using(public.is_workspace_member(workspace_id)); create policy cost_items_member_read on public.cost_items for select to authenticated using(public.is_workspace_member(workspace_id)); create policy cash_flow_entries_member_read on public.cash_flow_entries for select to authenticated using(public.is_workspace_member(workspace_id)); create policy cost_baselines_member_read on public.cost_baselines for select to authenticated using(public.is_workspace_member(workspace_id));
grant select on public.schedule_control_sets,public.schedule_versions,public.schedule_tasks,public.schedule_dependencies,public.schedule_baselines,public.cost_control_sets,public.cost_versions,public.cost_items,public.cash_flow_entries,public.cost_baselines to authenticated;
revoke insert,update,delete on public.schedule_control_sets,public.schedule_versions,public.schedule_tasks,public.schedule_dependencies,public.schedule_baselines,public.cost_control_sets,public.cost_versions,public.cost_items,public.cash_flow_entries,public.cost_baselines from authenticated;
revoke all on function public.save_schedule_control(uuid,integer,jsonb,jsonb,jsonb,jsonb),public.save_cost_control(uuid,integer,jsonb,jsonb,jsonb),public.approve_delivery_baseline(uuid,text,integer,text),public.begin_delivery_revision(uuid,text,integer,text) from public;
grant execute on function public.save_schedule_control(uuid,integer,jsonb,jsonb,jsonb,jsonb),public.save_cost_control(uuid,integer,jsonb,jsonb,jsonb),public.approve_delivery_baseline(uuid,text,integer,text),public.begin_delivery_revision(uuid,text,integer,text) to authenticated;
commit;
