begin;

create table public.ai_conversations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,channel text not null check(channel in('text','browser_voice','phone')),title text,retention_mode text not null default 'standard',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.ai_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.ai_conversations(id) on delete cascade,role text not null check(role in('user','assistant','tool')),content jsonb not null,citations jsonb not null default '[]',created_at timestamptz not null default now());
create table public.ai_action_proposals(id uuid primary key default gen_random_uuid(),conversation_id uuid references public.ai_conversations(id) on delete cascade,workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,requested_by uuid not null references auth.users(id),tool_name text not null,risk_level text not null check(risk_level in('R0','R1','R2','R3','R4')),args jsonb not null default '{}',status text not null default 'draft',idempotency_key text,executed_at timestamptz,created_at timestamptz not null default now());
create unique index ai_action_idempotency_idx on public.ai_action_proposals(workspace_id,idempotency_key);
create table public.ai_audit_events(id bigint generated always as identity primary key,workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,actor_id uuid references auth.users(id) on delete set null,event_type text not null,channel text,details jsonb not null default '{}',created_at timestamptz not null default now());
create table public.ai_feedback(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,conversation_id uuid not null references public.ai_conversations(id) on delete cascade,message_id uuid references public.ai_messages(id) on delete set null,user_id uuid not null references auth.users(id),rating text not null check(rating in('helpful','incorrect')),comment text not null default '',created_at timestamptz not null default now());
create table public.ai_automations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,template_id text not null,name text not null,enabled boolean not null default false,config jsonb not null default '{}',approval_required boolean not null default true,updated_by uuid not null references auth.users(id),archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index ai_automations_scope_template_idx on public.ai_automations(workspace_id,project_id,template_id);
create index ai_conversations_scope_idx on public.ai_conversations(workspace_id,project_id,updated_at desc);
create index ai_audit_scope_idx on public.ai_audit_events(workspace_id,project_id,created_at desc);

alter table public.ai_conversations enable row level security;alter table public.ai_messages enable row level security;alter table public.ai_action_proposals enable row level security;alter table public.ai_audit_events enable row level security;alter table public.ai_feedback enable row level security;alter table public.ai_automations enable row level security;
create policy ai_conversations_member_all on public.ai_conversations for all to authenticated using(public.is_workspace_member(workspace_id) and user_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and user_id=auth.uid());
create policy ai_messages_owner_all on public.ai_messages for all to authenticated using(exists(select 1 from public.ai_conversations c where c.id=conversation_id and c.user_id=auth.uid())) with check(exists(select 1 from public.ai_conversations c where c.id=conversation_id and c.user_id=auth.uid()));
create policy ai_actions_member_read on public.ai_action_proposals for select to authenticated using(public.is_workspace_member(workspace_id));
create policy ai_audit_member_read on public.ai_audit_events for select to authenticated using(public.is_workspace_member(workspace_id));
create policy ai_feedback_self_all on public.ai_feedback for all to authenticated using(user_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and user_id=auth.uid());
create policy ai_automations_member_read on public.ai_automations for select to authenticated using(public.is_workspace_member(workspace_id));
revoke all on public.ai_conversations,public.ai_messages,public.ai_action_proposals,public.ai_audit_events,public.ai_feedback,public.ai_automations from anon,authenticated;
grant select on public.ai_conversations,public.ai_messages,public.ai_action_proposals,public.ai_audit_events,public.ai_feedback,public.ai_automations to authenticated;
grant all on public.ai_conversations,public.ai_messages,public.ai_action_proposals,public.ai_audit_events,public.ai_feedback,public.ai_automations to service_role;
grant usage,select on sequence public.ai_audit_events_id_seq to service_role;

commit;
